SOURCES      = warframeAlert/components/common/Accolyte.py \
               warframeAlert/components/common/Alert.py \
               warframeAlert/components/common/BountyBox.py \
               warframeAlert/components/common/ClanEvent.py \
               warframeAlert/components/common/Countdown.py \
               warframeAlert/components/common/DailyDeals.py \
               warframeAlert/components/common/Event.py \
               warframeAlert/components/common/EventReward.py \
               warframeAlert/components/common/FissureBox.py \
               warframeAlert/components/common/GlobalUpgrade.py \
               warframeAlert/components/common/HubEvent.py \
               warframeAlert/components/common/Invasion.py \
               warframeAlert/components/common/InvasionNode.py \
               warframeAlert/components/common/MessageBox.py \
               warframeAlert/components/common/PvPMissionBox.py \
               warframeAlert/components/common/PvPAlternativeMissionBox.py \
               warframeAlert/components/common/ReconstructionRelayEvent.py \
               warframeAlert/components/common/RelicBox.py \
               warframeAlert/components/common/SalesBox.py \
               warframeAlert/components/common/SeasonBox.py \
               warframeAlert/components/common/ScoreEvent.py \
               warframeAlert/components/common/SimarisTarget.py \
               warframeAlert/components/common/SortieBox.py \
               warframeAlert/components/common/SortieMissionBox.py \
               warframeAlert/components/common/SpecialAlert.py \
               warframeAlert/components/common/SquadLinkEvent.py \
               warframeAlert/components/common/SyndicateBox.py \
               warframeAlert/components/common/TwitchBox.py \
               warframeAlert/components/tab/AccolyteWidgetTab.py \
               warframeAlert/components/tab/BaroWidgetTab.py \
               warframeAlert/components/tab/BountyWidgetTab.py \
               warframeAlert/components/tab/EventsWidgetTab.py \
               warframeAlert/components/tab/FissureWidgetTab.py \
               warframeAlert/components/tab/InvasionWidgetTab.py \
               warframeAlert/components/tab/NewsWidgetTab.py \
               warframeAlert/components/tab/NightwaveWidgetTab.py \
               warframeAlert/components/tab/OtherWidgetTab.py \
               warframeAlert/components/tab/PvPWidgetTab.py \
               warframeAlert/components/tab/SalesWidgetTab.py \
               warframeAlert/components/tab/SortieWidgetTab.py \
               warframeAlert/components/tab/SyndicateWidgetTab.py \
               warframeAlert/components/widget/AlertWidget.py \
               warframeAlert/components/widget/BountyWidget.py \
               warframeAlert/components/widget/GeneralInfoWidget.py \
               warframeAlert/components/widget/HubWidget.py \
               warframeAlert/components/widget/PvPAlternativeWidget.py \
               warframeAlert/components/widget/PvPTournamentWidget.py \
               warframeAlert/components/widget/RelayStationWidget.py \
               warframeAlert/components/widget/RelicWidget.py \
               warframeAlert/components/widget/SearchRelicWidget.py \
               warframeAlert/components/widget/TwitchPromoWidget.py \
               warframeAlert/components/widget/UpdateProgramWidget.py \
               warframeAlert/components/widget/UpdateRequiredFilesWidget.py \
               warframeAlert/services/menuService.py \
               warframeAlert/services/networkService.py \
               warframeAlert/services/notificationService.py \
               warframeAlert/services/tabService.py \
               warframeAlert/services/trayService.py \
               warframeAlert/services/updateFileService.py \
               warframeAlert/services/updateProgramService.py \
               warframeAlert/services/updateService.py \
               warframeAlert/utils/commonUtils.py \
               warframeAlert/utils/gameTranslationUtils.py \
               warframeAlert/utils/stringUtils.py \
               warframeAlert/utils/timeUtils.py \
               warframeAlert/utils/warframeUtils.py \
               warframeAlert/utils/warframeFileUtils.py \
               warframeAlert/WarframeAlert.py

TRANSLATIONS = warframeAlert/translation/warframeAlert_en.ts \
               warframeAlert/translation/warframeAlert_it.ts