# -*- coding: utf-8 -*-

MAP_TYPE = {
    "OrokinTower": {"it": "Torre Orokin", "en": "Orokin Tower"},
    "OrokinMoon": {"it": "Luna", "en": "Moon"},
    "OrokinVoid": {"it": "Void", "en": "Void"},
    "OrokinDerelict": {"it": "Relitto Orokin", "en": "Orokin Derelict"},

    "CorpusShip": {"it": "Nave Corpus", "en": "Corpus Ship"},
    "CorpusGasCity": {"it": "Citta' di Gas Corpus", "en": "Corpus Gas City"},
    "CorpusIcePlanet": {"it": "Pianeta Ghiacciato Corpus", "en": "Corpus Ice Planet"},
    "CorpusOutpost": {"it": "Insediamento Corpus", "en": "Corpus Outpost"},
    "TR": {"it": "Nave Corpus (Archwing)", "en": "Corpus Ship (Archwing)"},

    "GrineerForest": {"it": "Foresta Grineer", "en": "Grineer Forest"},
    "GrineerSettlement": {"it": "Insediamento Grineer", "en": "Grineer Settlement"},
    "GrineerAsteroid": {"it": "Asteroide Grineer", "en": "Grineer Asteroid"},
    "GrineerGalleon": {"it": "Galeone Grineer", "en": "Grineer Galleon"},
    "GrineerFortress": {"it": "Fortezza Kuva", "en": "Kuva Fortress"},
    "GrineerShipyards": {"it": "Cantiere Navale Grineer", "en": "Grineer Shipyards"},
    "GrineerOcean": {"it": "Lab. Sottomarini Grineer", "en": "Grineer Submarine Lab"},
    "SpaceGrineer": {"it": "Spazio Aperto (Archwing)", "en": "Space (Archwing)"},

    "InfestedCorpusShip": {"it": "Nave Corpus Infested", "en": "Infested Corpus Ship"},

    "CorpusToCorpusInfested": {"it": "Nave Corpus-Infested", "en": "Corpus-Infested Ship"},
    "CorpusToGrinee": {"it": "Nave Corpus-Grineer", "en": "Corpus-Grineer Ship"},
    "GrineerToCorpus": {"it": "Nave Grinner-Corpus", "en": "Grineer-Corpus Ship"},

    "CivilianHubs": {"it": "Cetus", "en": "Cetus"},
    "Plains": {"it": "Pianure di Eidolon", "en": "Plains of Eidolon"},
    "Eidolon": {"it": "Pianure di Eidolon", "en": "Plains of Eidolon"},
    "Solaris": {"it": "Solaris", "en": "Solaris"},
    "VenusLandscape": {"it": "Orbs Vallis", "en": "Orbs Vallis"},
}

ALERT_INFO = {
    "/Lotus/Language/Alerts/LotusGiftDesc": {"it": "Dono di Lotus", "en": "Lotus Gift"},
    "/Lotus/Language/Alerts/DarvoRescueTitle": {"it": "Legami duri a morire", "en": "Ties to die"},
    "/Lotus/Language/Alerts/DarvoMobileDefenseTitle": {"it": "Un favore per Darvo", "en": "A favor for Darvo"},
    "/Lotus/Language/Alerts/GrineerLootShip": {"it": "Nave del Tesore Grineer", "en": "Grineer Treasury Ship"},
    "/Lotus/Language/Alerts/CorpusLootShip": {"it": "Nave del Tesore Corpus", "en": "Corpus Treasury Ship"},
    "/Lotus/Language/Alerts/NightmareAlertDesc": {"it": "Trovata Mod Nightmare", "en": "Found Nightmare Mod"},
    "/Lotus/Language/Alerts/OrokinOverload": {"it": "Sovraccarico Orokin", "en": "Orokin Overload"},
    "/Lotus/Language/Alerts/CouncilChallengeDesc": {"it": "Sfida del Design Council", "en": "Design Council Challenge"},
    "Design Council Challenge": {"it": "Sfida del Design Council", "en": "Design Council Challenge"},
    "/Lotus/Language/Alerts/DefenseDesc1": {"it": "Agguato al Cargo", "en": "Ambushing the Cargo"},
    "/Lotus/Language/Alerts/DefenseDesc2": {"it": "Attacca Centro di Ricerca", "en": "Attack Research Center"},
    "/Lotus/Language/Alerts/DefenseDesc3": {"it": "Agguato all'Impianto Minerario",
                                            "en": "Ambushing the Mining Center"},
    "/Lotus/Language/Alerts/DefenseDesc4": {"it": "Difendi i dati", "en": "Defend the data"},
    "/Lotus/Language/Alerts/DefenseDesc5": {"it": "Warframe Compromesso", "en": "Compromised Warframe"},
    "/Lotus/Language/Alerts/DefenseDesc6": {"it": "Informatore Nemico Compromesso",
                                            "en": "Enemy Informant Compromised"},
    "/Lotus/Language/Alerts/DefenseDesc7": {"it": "Operativo Tenno Compromesso", "en": "Tenno Operative Compromised"},
    "/Lotus/Language/Alerts/DefenseDesc8": {"it": "Proteggi Nave Cargo", "en": "Protect Cargo Ship"},
    "/Lotus/Language/Alerts/DefenseDesc9": {"it": "Attendi i Rinforzi", "en": "Wait the Reinforcements"},
    "/Lotus/Language/Alerts/DefenseDesc10": {"it": "Difendi Laboratorio Nemico", "en": "Defend Enemy Laboratory"},
    "/Lotus/Language/Alerts/DefenseDesc11": {"it": "Proteggi l'Artefatto'", "en": "Protect the Artifact"},
    "/Lotus/Language/Alerts/DefenseDesc12": {"it": "Deposito Armi Compromesso", "en": "Weapon Depot Compromised"},
    "/Lotus/Language/Alerts/DefenseDesc13": {"it": "Proteggi l'Avamposto Minerario di Rubedo",
                                             "en": "Protect the Rubedo Mining Outpost"},
    "/Lotus/Language/Alerts/DefenseDesc14": {"it": "Proteggi il Relitto", "en": "Protect the Relict"},
    "/Lotus/Language/Alerts/DefenseDesc15": {"it": "Respingi l'Attacco Nemico", "en": "Repel the enemy attack"},
    "/Lotus/Language/Alerts/DefenseDesc16": {"it": "Proteggi la Ricerca Scientifica", "en": "Protect the research"},
    "/Lotus/Language/Alerts/DefenseDesc17": {"it": "Imboscata alla Rotaia Solare", "en": "Solar Rail Ambush"},
    "/Lotus/Language/Alerts/DefenseDesc18": {"it": "Proteggi l'Ostaggio'", "en": "Protect the Hostage"},
    "/Lotus/Language/Alerts/DefenseDesc19": {"it": "Proteggi Dati Sensibili", "en": "Protect Sensitive Data"},
    "/Lotus/Language/Alerts/DefenseDesc20": {"it": "Proteggi il Nucleo del Computer", "en": "Protect Computer Core"},
    "/Lotus/Language/Alerts/DefenseDesc21": {"it": "Ricerca Compromessa", "en": "Research Compromised"},
    "/Lotus/Language/Alerts/SurvivalDesc1": {"it": "Sopravvivi o Muori", "en": "Survive or Die"},
    "/Lotus/Language/Alerts/SpeedRun": {"it": "Sfida a Tempo", "en": "Speed Run"},
}

ALERT_WEAPON_RESTRICTION = {
    "/Lotus/Weapons/Tenno/LotusLongGun": {"it": "Solo Arma Primaria", "en": "Primary Weapon Only"},
    "/Lotus/Weapons/Tenno/Rifle/LotusAssaultRifle": {"it": "Solo Fucile d'Assalto", "en": "Assault Rifle Only"},
    "/Lotus/Weapons/Tenno/Rifle/LotusSniperRifle": {"it": "Solo Cecchino", "en": "Sniper Only"},
    "/Lotus/Weapons/Tenno/Shotgun/LotusShotgun": {"it": "Solo Fucile a Pompa", "en": "Shotgun Only"},
    "/Lotus/Weapons/Tenno/Bows/LotusBow": {"it": "Solo Arco", "en": "Bow Only"},
    "/Lotus/Weapons/Tenno/Pistol/LotusPistol": {"it": "Solo Pistola", "en": "Pistol Only"},
    "/Lotus/Weapons/Tenno/Melee/PlayerMeleeWeapon": {"it": "Solo Corpo a Corpo", "en": "Melee Only"},
    "/Lotus/Types/Game/LotusMeleeWeapon": {"it": "Solo Corpo a Corpo", "en": "Melee Only"},
}

ALERT_FX = {
    "LightningStorm": {"it": "Fulmini", "en": "Lightning Storm"},
    "DarkFog": {"it": "Nebbia Fitta", "en": "Dark Fog"},
}

ALERT_ENEMY = {
    "/Lotus/Types/Enemies/Grineer/AIWeek/ShieldLancer": "Shield Launcher",
    "/Lotus/Types/Enemies/Grineer/AIWeek/Avatars/ShieldLancer": "Shield Launcher",
    "/Lotus/Types/Enemies/Corpus/Drones/AIWeek/SuicideDroneAgent": "Oxium Osprey",
    "/Lotus/Types/Enemies/Infested/AiWeek/Quadrupeds/Quadruped": "Charger",
}

ALERT_BOSS = {
    "/Lotus/Types/Enemies/Grineer/Vip/CaptainVorBossAgent": {"it": "Capitano Vor", "en": "Captain Vot"},
    "/Lotus/Types/Enemies/Corpus/QuadRobot/QuadRobotAgent": {"it": "Jackal", "en": "Jackal"},
    "/Lotus/Types/Enemies/Grineer/Vip/Hek/HekBipedAgent": {"it": "Vay Hek", "en": "Vay Hek"},
    "/Lotus/Types/Enemies/Grineer/Vip/BossLechKrilAgent": {"it": "Lt. Lech Kril", "en": "Lt. Lech Kril"},
    "/Lotus/Types/Enemies/Corpus/Spaceman/Vip/SniperAgent": {"it": "Il Sergente", "en": "The Sergent"},
    "/Lotus/Types/Enemies/Grineer/Vip/KrillAndVorBossFight": {"it": "Lt. Lech Kril e Capitano Vor",
                                                              "en": "Lt. Lech Kril anc Captain Vor"},
    "/Lotus/Types/Enemies/Corpus/Vip/AladV/AladBossAgent": {"it": "Alad V", "en": "Alad V"},
    "/Lotus/Types/Enemies/Corpus/Drones/Vip/RaptorPack": {"it": "Raptor", "en": "Raptor"},
    "/Lotus/Types/Enemies/Grineer/Vip/SargasRuk/SargasRukBossAgent": {"it": "Generale Sargas Ruk", "en": "Sargas Ruk"},
    "/Lotus/Types/Enemies/Grineer/Vip/TylRegor/TylRegorAgent": {"it": "Tyl Regor", "en": "Tyl Regor"},
    "/Lotus/Types/Enemies/Corpus/Vip/Hyena/HyenaPack": {"it": "Branco Hyena", "en": "Hyena Pack"},
    "/Lotus/Types/Enemies/Corpus/Vip/Ambulas/BossAmbulasRangedAgent": {"it": "Ambulas", "en": "Ambulas"},
    "/Lotus/Types/Enemies/Grineer/Vip/KelaDeThaym/KelaDeThaymAgent": {"it": "Kela de Thaym", "en": "Kela de Thaym"},
    "/Lotus/Types/Enemies/Infested/Vip/J3Golem/JuniorGolemSpaceAgent": {"it": "Jordas Golem", "en": "Jordas Golem"},
    "/Lotus/Types/Enemies/Corpus/Vip/InfestedAladV/InfestedAladBossAgent": {"it": "Mutualist Alad V",
                                                                            "en": "Mutualist Alad V"},
    "/Lotus/Types/Enemies/Infested/Vip/GolemFullAgent": {"it": "Lephantis", "en": "Lephantis"},
    "/Lotus/Types/Enemies/Infested/Vip/QuadrupedVIP": {"it": "Fulmini", "en": "Lightning Storm"},
    "/Lotus/Types/Enemies/Infested/AiWeek/Quadrupeds/Juggernaut": {"it": "Juggernaut", "en": "Juggernaut"},
    "/Lotus/Types/Enemies/Infested/AiWeek/Quadrupeds/JuggernautBoss": {"it": "Juggernaut Behemoth",
                                                                       "en": "Juggernaut Behemoth"},
    "/Lotus/Types/Enemies/Infested/AiWeek/Quadrupeds/JuggernautTacAlert": {"it": "Jack'O Naut", "en": "Jack'O Naut"},
    "/Lotus/Types/Enemies/Grineer/Vip/VorTwo/VorTwoBossAgent": {"it": "Corrupted Vor", "en": "Corrupted Vor"},
    "/Lotus/Types/Enemies/Stalker/SentientStalkerAgent": {"it": "Shadow Stalker", "en": "Shadow Stalker"},
    "/Lotus/Types/Enemies/Stalker/LisetStalkerAgent": {"it": "Shadow Stalker", "en": "Shadow Stalker"},
    "/Lotus/Types/Enemies/Grineer/DeathSquad/DeathSquadA": {"it": "Vem Tabook", "en": "Vem Tabook"},
    "/Lotus/Types/Enemies/Corpus/QuadRobot/MiniBoss/QuadRobotMiniBossAgent": {"it": "Linx", "en": "Linx"},
    "/Lotus/Types/Enemies/Grineer/Vip/JetpackSisters/JetpackSisters": {"it": "Sprang e Ven'kra Tel",
                                                                       "en": "Sprang and Ven'kra Tel"},
    "/Lotus/Types/Enemies/Corpus/SpecialEvents/ArmoredJackal/ArmoredJackalAgent": {"it": "Razorback",
                                                                                   "en": "Razorback"},
    "/Lotus/Types/Enemies/Grineer/SpecialEvents/WolfSentientStalkerAgent": {"it": "Wolf di Saturn Six",
                                                                            "en": "Wolf of Saturn Six"},
    "/Lotus/Types/Enemies/Grineer/SpecialEvents/WolfGangster": {"it": "Fuggitivo Saturn Six",
                                                                "en": "Saturn Six Fugitive"},
    "/Lotus/Types/Enemies/Sentients/Ropalolyst/SentientRopalolystAgent": {"it": "Ropalolyt", "en": "Ropalolyt"},

}

ALERT_VIP_AGENT = {
    "/Lotus/Types/Enemies/TennoReplicants/SyndicateAllies/PalladinoDefenseAgent": {"it": "Palladino",
                                                                                   "en": "Palladino"},
    "/Lotus/Types/Enemies/Quests/PriestQuest/EmotionSpecterAgent": {"it": "Emozioni di Rell", "en": "Rell Emotion"},
    "/Lotus/Types/Enemies/Corpus/Spaceman/CivilianAgentCaptureEvent": {"it": "Scout Corpus", "en": "Corpus Scout"},
    "/Lotus/Types/Enemies/CaptureTargets/CaptureTargetMaRooAgent": {"it": "Maroo", "en": "Maroo"},
    "/Lotus/Types/Enemies/TennoReplicants/TennoReplicantGunslingerAgent": {"it": "Infested Mesa",
                                                                           "en": "Infested Mesa"},
    "/Lotus/Types/Enemies/TennoReplicants/TennoReplicantChromaAgentDerelict": {"it": "Infested Chroma",
                                                                               "en": "Infested Chroma"},
    "/Lotus/Types/Friendly/Agents/PedestalMachineDefenseAgent": {"it": "Macchina Arcana", "en": "Arcane Machine"},
    "/Lotus/Types/Friendly/Agents/CoreDefenseBombAgent": {"it": "Fulmini", "en": "Lightning Storm"},
    "/Lotus/Types/Friendly/Agents/DragonQuestRescueAgent": {"it": "Sentinelle di Symaris", "en": "Symaris Sentinels"},
    "/Lotus/Types/Enemies/Grineer/Vip/Teshin/TeshinShadowAgent": {"it": "Spettro Tenshin", "en": "Tenshin Specter"},
    "/Lotus/Types/Enemies/Infested/AiWeek/Ancients/SpawningAncientMiniboss": {"it": "Arcane Boiler",
                                                                              "en": "Arcane Boiler"},
    "/Lotus/Types/Friendly/ClemAgent": {"it": "Clem", "en": "Clem"},
    "/Lotus/Types/Friendly/Rescue/ClemRescueAgent": {"it": "Clem", "en": "Clem"},
    "/Lotus/Types/Friendly/Rescue/RescueAgentDarvo": {"it": "Darvo", "en": "Darvo"},
    "/Lotus/Types/Friendly/Rescue/RescueAgentMaleLegacy": {"it": "Ostaggio", "en": "Hostage"},
    "/Lotus/Types/Friendly/Agents/EventDefenseAgent": {"it": "Artefatto", "en": "Artifact"},
    "/Lotus/Types/Friendly/Agents/EventDefenseAgentGrineer": {"it": "Artefatto", "en": "Artifact"},
    "/Lotus/Types/Friendly/Agents/DefenseAgent": {"it": "Modulo Criogenico Warframe",
                                                  "en": "Cryogenic Warframe Module"},
    "/Lotus/Types/Enemies/Corpus/Vip/DefenseTargetAladV/DefenseTargetAladAgent": {"it": "Alad V", "en": "Alad V"},
    "/Lotus/Types/Enemies/CaptureTargets/CaptureTargetGrineerFortAAgent": {"it": "Obiettivo Grineer",
                                                                           "en": "Grineer Target"},
    "/Lotus/Types/Enemies/Grineer/AIWeek/ManicRocketBombard": {"it": "Maniac Bombard", "en": "Maniac Bombard"},
    "/Lotus/Types/Enemies/Quests/SacrificeQuest/UmbraChaseAgent": {"it": "Umbra", "en": "Umbra"},
    "/Lotus/Types/Friendly/Agents/CoreDefenseAgent": {"it": "Nucleo Energetico Orokin",
                                                      "en": "Orokin Energy Core"},
}

ALERT_LEVEL_AURA = {
    "/Lotus/Upgrades/Mods/DirectorMods/BossDropReductionAura": {"it": "Nessun Drop dai Boss",
                                                                "en": "No drop from boss"},
    "/Lotus/Upgrades/Mods/DirectorMods/SentientDropReductionAura": {"it": "Nessun Drop dai Sentient",
                                                                    "en": "No drop from Sentient"},
    "/Lotus/Upgrades/Mods/DirectorMods/OpLinkSentientFactionDropReductionAura": {"it": "Nessun Drop dai Sentient",
                                                                                 "en": "No drop from Sentient"},
    "/Lotus/Upgrades/Mods/DirectorMods/ShadowEnemyAura": {"it": "Appaiono Nemici Ombra", "en": "Spawn Shadow Enemies"},
    "/Lotus/Upgrades/Mods/DirectorMods/ShadowEnemyAuraHarrow": {"it": "Appaiono Nemici Ombra di Harrow",
                                                                "en": "Spawn Harrow Shadow Enemies"},
    "/Lotus/Upgrades/Mods/DirectorMods/HalloweenLevelAura": {"it": "I Nemici hanno decorazioni di Halloween",
                                                             "en": "Enemies have Halloween decoration"},
    "/Lotus/Upgrades/Mods/DirectorMods/DropAmountOverrideAura": {"it": "Poteri Operatore Infiniti",
                                                                 "en": "Infinite Operator Power"},
    "/Lotus/Upgrades/Mods/DirectorMods/HighDamageEnemyLevelAura": {"it": "Danno Nemico Aumentato (300%)",
                                                                   "en": "Auguamented Enemy Damage (300%)"},
    "/Lotus/Upgrades/Mods/DirectorMods/EnergyLimitAura": {"it": "Energia Limitata (50)", "en": "Energy Cap (50)"},
    "/Lotus/Upgrades/Mods/DirectorMods/FastEnemyLevelAura": {"it": "Nemici piu' Veloci", "en": "Faster Enemies"},
    "/Lotus/Upgrades/Mods/DirectorMods/HalfShieldsLevelAura": {"it": "Metà Scudi", "en": "Half Shield"},
    "/Lotus/Upgrades/Mods/DirectorMods/HalloweenBonusLevelAura": {"it": "Nebbia, Nessuna Abilita', Nessuna Arma",
                                                                  "en": "Fog, No Ability, No Weapon"},
    "/Lotus/Upgrades/Mods/DirectorMods/HardModeLevelAura": {"it": "+150% Salute/Armatura/Scudi Nemici",
                                                                  "en": "+150% Enemy Health/Armour/Shield"},
    "/Lotus/Upgrades/Mods/DirectorMods/HardModeEnemyLevelAura": {"it": "Livello Nemici +100",
                                                                 "en": "Enemy Level +100"}
}
