# -*- coding: utf-8 -*-

RARITY = {"COMMON": {"it": "Comune", "en": "Common"},
          "UNCOMMON": {"it": "Non Comune", "en": "Uncommon"},
          "RARE": {"it": "Raro", "en": "Rare"},
          "LEGENDARY": {"it": "Leggendario", "en": "Legendary"},
          }

RELICS = {"LITH": "Lith",
          "NEO": "Neo",
          "MESO": "Meso",
          "AXI": "Axi",
          "REQUIEM": "Requiem",
          "RELIC": "Reliquia",
          }

LENS = {"MADURAI": "Madurai",
        "VAZARIN": "Vazarin",
        "ZENURIK": "Zenurik",
        "NARAMON": "Naramon",
        "UNAIRU": "Unairu",
        "LENS": "Lente",
        "GREATER": "Maggiore",
        "EIDOLON": "Eidolon",
        "LUA": "Lua",
        }


RESOURCES = {
        "ALLOY PLATE": "Piastre in Lega",
        "ARGON CRYSTAL": "Cristallo di Argon",
        "CIRCUITS": "Circuiti",
        "CONTROL MODULE": "Modulo di Controllo",
        "CRYOTIC": "Cryotic",
        "FERRITE": "Ferrite",
        "GALLIUM": "Gallio",
        "MORPHICS": "Morfidi",
        "NANO SPORES": "Nanospore",
        "NEURAL SENSORS": "Sensori Neurali",
        "NEURODES": "Neurode",
        "OROKIN CELL": "Cella Orokin",
        "OXIUM": "Oxium",
        "PLASTIDS": "Plastidi",
        "POLYMER BUNDLE": "Kit Polimeri",
        "RUBEDO": "Rubedo",
        "SALVAGE": "Rottami",  # prima Reperti
        "TELLURIUM": "Tellurio",  # prima Tellurium
        "HEXENON": "Hexenon",
        "NITAIN EXTRACT": "Estratto Nitain",
        "DETONITE AMPULE": "Ampolla di Detonite",
        "FIELDRON SAMPLE": "Campione Fieldron",
        "MUTAGEN SAMPLE": "Campione Mutagene",
        "DETONITE INJECTOR": "Iniettore di Detonite",
        "FIELDRON": "Fieldron",
        "MUTAGEN MASS": "Massa Mutagene",
        "NAV COORDINATE": "Coordinate Nav",
        "MUTALIST ALAD V NAV COORDINATE": "Coordinate Nav Mutualist Alad V",
        "KUVA": "Kuva",
        "VOID TRACES": "Tracce Void",
        "SYNTHETIC EIDOLON SHARD": "Scheggia di Eidolon Sintetica",
        "CETUS WISP": "Cetus Wisp",
        "BREATH OF THE EIDOLON": "Soffio di Eidolon",
        "KUAKA SPINAL CLAW": "Artiglio Spinale Kuaca",
        "CONDROC WING": "Ala di Condrod",
        "NISTLEPOD": "Nistlepod",
        "MAPRICO": "Maprico",
        "IRADITE": "Iradite",
        "GROKDRUL": "Grokdrul",
        "PYROTIC ALLOY": "Lega di Pyrotic",
        "COPRITE ALLOY": "Lega di Coprite",
        "FERSTEEL ALLOY": "Lega di Fersteel",
        "TEAR AZURITE": "Azzurrite a Goccia",
        "ESHER DEVAR": "Esher Devar",
        "MARQUISE VERIDOS": "Veridos Taglio Marquise",
        "AUROXIUM ALLOY": "Lega di Auroxium",
        "FISH SCALES": "Squame di Pesce",
        "MAWFISH BONES": "Ossa di Mawfish",
        "KHUT-KHUT VENOM SAC": "Sacca Velenifera di Khut-Khut",
        "YOGWUN STOMACH": "Stomaco di Yogwun",
        "CHARC ELECTROPLAX": "Charc Elettrociti",
        "GOOPOLLA SPLEEN": "Goopolla Milza",
        "TRALOK EYES": "Occhi di Tralok",
        "MORTUS HORN": "Corno di Mortus",
        "BOOT": "Stivale",
        "NORG": "Norg",
        "FASS RESIDUE": "Residuo Fass",
        "VOME RESIDUE": "Residuo Vome",
        "TRAINING DEBT-BOND": "Obbligazioni di Formazione",
        "SHELTER DEBT-BOND": "Obbligazioni di Rifugio",
        "MEDICAL DEBT-BOND": "Obbligazioni Mediche",
        "ADVANCES DEBT-BOND": "Obbligazioni di Anticipo",
        "FAMILIAL DEBT-BOND": "Obbligazioni Familiari",
        "VEGA TOROID": "Toroid Vega",
        "CALDA TOROID": "Toroid Calda",
        "SOLA TOROID": "Toroid Sola",
        "GYROMAG SYSTEMS": "Sistemi Giromag",
        "ATMO SYSTEMS": "Sistemi Armo",
        "REPELLER SYSTEMS": "Sistemi Repeller",
        "TEPA NODULE": "Nodulo Tepa",
        "MYTOCARDIA SPORE": "Spora Mytocardia",
        "GORGARICUS SPORE": "Spora Gorgaricus",
        "THERMAL SLUDGE": "Residui Termici",
        "GANGLION": "Ganglion",
        "PUSTULITE": "Pustulite",
        "LUCENT TEROGLOBE": "Teroglobe Lucente",
        "OROKIN ORIENTATION MATRIX": "Matrice Orientamento Orokin",
        "OROKIN BALLISTICS MATRIX": "Matrice Balistica Orokin",
        "OROKIN ANIMUS MATRIX": "Matrice Animus Orokin",
        "SCINTILLANT": "Scintillante",
        "NARMER ISOPLAST": "Isoplast Narmer",
        "CUBIC DIODES": "Diodi Cubici",
        "TITANIUM": "Titanio",
        "ISOS": "Isos",
        "ASTERITE": "Asterite",
        "AUCRUX CAPACITORS": "Condensatori Aucrux",
        "NULLSTONES": "Nullstone",
        "CARBIDES": "Carburi",
        "GALLOS RODS": "Barre di Gallos",
        "KOMMS": "Trasmettitori",
        }


ITEMS = {
    "CREDITS CACHE": "Crediti",
    "ENDO": "Endo",
    "DIRAC": "Dirac",
    "HEALTH RESTORE (LARGE)": "Ripristino Salute (Grande)",
    "OMNI AMMO BOX": "Scatola Munizioni Universale",
    "FORMA": "Forma",
    "FORMA BLUEPRINT": "Forma (Schema)",
    "AURA FORMA BLUEPRINT": "Aura Forma (Schema)",
    "EXILUS WARFRAME ADAPTER": "Adattatore Exilus Warframe",
    "EXILUS WEAPON ADAPTER BLUEPRINT": "Adattatore Exilus Arma (Schema)",
    "OROKIN REACTOR BLUEPRINT": "Reattore Orokin (Schema)",
    "OROKIN CATALYST BLUEPRINT": "Catalizzatore Orokin (Schema)",
    "AYA": "Aya",
    "VAPOR SPECTER BLUEPRINT": "Spettro Vapor (Schema)",
    "PHASE SPECTER BLUEPRINT": "Spettro Phase (Schema)",
    "FORCE SPECTER BLUEPRINT": "Spettro Force (Schema)",
    "COSMIC SPECTER BLUEPRINT": "Spettro Cosmic (Schema)",
    "CLEM CLONE BLUEPRINT": "Clone Clem (Schema)",
    "CHARGER SPECTER BLUEPRINT": "Spettro Charger (Schema)",
    "ANCIENT HEALER SPECTER BLUEPRINT": "Spettro Ancient Healer (Schema)",
    "DAY OF THE DEAD SIGIL": "Sigillo Giorno dei Morti",
    "XIPHOS ENGINES BLUEPRINT": "Xiphos Motori (Schema)",
    "XIPHOS FUSELAGE BLUEPRINT": "Xiphos Fusoliera (Schema)",
    "XIPHOS AVIONICS BLUEPRINT": "Xiphos Avioniche (Schema)",
    "SCIMITAR ENGINES BLUEPRINT": "Scimitar Motori (Schema)",
    "SCIMITAR FUSELAGE BLUEPRINT": "Scimitar Fusoliera (Schema)",
    "SCIMITAR AVIONICS BLUEPRINT": "Scimitar Avioniche (Schema)",
    "MANTIS ENGINES BLUEPRINT": "Mantis Motori (Schema)",
    "MANTIS FUSELAGE BLUEPRINT": "Mantis Fusoliera (Schema)",
    "MANTIS AVIONICS BLUEPRINT": "Mantis Avioniche (Schema)",
    "KAVAT GENETIC CODE": "Codice Genetico Kavat",
    "KAVAT INCUBATOR UPGRADE SEGMENT BLUEPRINT": "Segmento Potenziamento Incubatore Kavat (Schema)",
    "PHERLIAC PODS BLUEPRINT": "Pherliac Pod (Schema)",
    "PHERLIAC PODS": "Pherliac Pod",
    "PULSATING TUBERCLES": "Tubercoli Pulsanti",
    "INFECTED PALPATORS": "Palpatori Infested",
    "CHITINOUS HUSK": "Guscio Chitinoso",
    "SEVERED BILE SAC": "Sacca Biliare Amputata",
    "KUBROW EGG": "Uovo Kubrow",
    "AFFINITY BOOSTER": "Booster Affinità",
    "RESOURCE DROP CHANCE BOOSTER": "Booster Possibilità Drop Risorse",
    "MOD DROP CHANCE BOOSTER": "Booster Possibilità Drop Mob",
    "AYATAN SAH SCULPTURE": "Scultura Ayatan Sah",
    "AYATAN AYR SCULPTURE": "Scultura Ayatan Ayr",
    "AYATAN ORTA SCULPTURE": "Scultura Ayatan Orta",
    "AYATAN VAYA SCULPTURE": "Scultura Ayatan Vaya",
    "AYATAN PIV SCULPTURE": "Scultura Ayatan Pic",
    "AYATAN ANASA SCULPTURE": "Scultura Ayatan Anasa",
    "AYATAN VALANA SCULPTURE": "Scultura Ayatan Valana",
    "AYATAN AMBER STAR": "Stella Ayatan Ambra",
    "ENCRYPTED JOURNAL FRAGMENT": "Frammento del Diario Criptato",
    "GRAVIMAG": "Gravimag",
    "RIVEN SLIVER": "Scheggia Riven",
    "CORRUPTED HOLOKEY": "Holokey Corrotta",
    "EARTH RESOURCE BUNDLE": "Bundle Risorse Terra",
    "VENUS RESOURCE BUNDLE": "Bundle Risorse Venere",
    "SATURN RESOURCE BUNDLE": "Bundle Risorse Saturno",
    "NEPTUNE RESOURCE BUNDLE": "Bundle Risorse Nettuno",
    "PLUTO RESOURCE BUNDLE": "Bundle Risorse Plutone",
    "VEIL RESOURCE BUNDLE": "Bundle Risorse Veil",
    "CORPUS SHIP FREIGHT SCENE": "Scenario Nave da Trasporto Corpus",
    "CORPUS SHIP ORBITAL CANNON SCENE": "Scenario Cannone Orbitale Nave Corpus",
    "CORPUS SHIP BRIDGE SCENE": "Scenario Ponte Nave Corpus",
    "CORPUS SHIP HANGAR SCENE": "Scenario Hangar Nave Corpus",
    "CORPUS DEPOSITORY SCENE": "Scenario Deposito Corpus",
    "GRINEER SEALAB CENTRIFUGE SCENE": "Scenario Centrifuga Laboratorio Marino Grineer",
    "GRINEER SETTLEMENT ARTILLERY SCENE": "Scenario Artiglieria Insediamento Grineer",
    "KUVA FORTRESS CREVICE SCENE": "Scenario Fenditura Fortezza Kuva",
    "BLAZING STEP EPHEMERA BLUEPRINT": "Ephemera Blazing Step (Schema)",
    "SEEDING STEP EPHEMERA BLUEPRINT": "Ephemera Seeding Step (Schema)",
    "MORTUUS SHOULDER GUARD": "Spallaccio Mortuus",
    "UNIVERSAL MEDALLION": "Medaglione Universale",
    "RUSH REPAIR DRONE": "Drone di Riparazione Immediata",
    "GRANUM CROWN DECORATION": "Decorazione Corona Granum",
    "EXEMPLAR GRANUM CROWN DECORATION": "Decorazione Corona Granum Eccelsa",
    "ZENITH GRANUM CROWN DECORATION": "Decorazione Corona Granum Zenith",
    "DAMAGED NECRAMECH WEAPON RECEIVER": "Castello Arma Necramech Danneggiato",
    "DAMAGED NECRAMECH WEAPON STOCK": "Calcio Arma Necramech Danneggiato",
    "DAMAGED NECRAMECH WEAPON BARREL": "Canna Arma Necramech Danneggiato",
    "INAROS OSIRIS HELMET": "Elmo Inaros Osiris",
    "LAVOS CORDATUS HELMET BLUEPRINT": "Elmo Lavos Cordatus (Schema)",

}


ITEM_PARTS = {
         "BLUEPRINT": "(Schema)",
         "NEUROPTICS": "Neurottiche",
         "SYSTEMS": "Sistemi",
         "CHASSIS": "Chassis",

         "HARNESS": "Imbracatura",
         "WINGS": "Ali",
         "CARAPACE": "Carapace",
         "CEREBRUM": "Cervello",
         "COLLAR": "Collare",
         "KUBROW": "Kubrow",

         "RECEIVER": "Castello",
         "RECEIVERS": "Castelli",
         "STOCK": "Calcio",
         "BARREL": "Canna",
         "BARRELS": "Canne",
         "HANDLE": "Manico",
         "BLADE": "Lama",
         "DUAL": "Dual",
         "TWIN": "Twin",
         "UPPER": "Superiore",
         "LOWER": "Inferiore",
         "LIMB": "Flettente",
         "GRIP": "Impugnatura",
         "STRING": "Corda",
         "HEAD": "Testa",
         "HILT": "Elsa",
         "LINK": "Connettore",
         "LINKS": "Collegamenti",
         "POUCH": "Fodero",
         "STARS": "Stelle",
         "ORNAMENT": "Ornamento",
         "CHAIN": "Catena",
         "BAND": "Fascia",
         "BUCKLE": "Fibbia",
         "HEATSINK": "Dissipatore",
         "GAUNTLET": "Guanto",
         "BLADES": "Lame",
         "DISC": "Disco",
         "CAPACITOR": "Capacitatore",
         "GUARD": "Scudo",
         "LEFT": "Sinistro",
         "RIGHT": "Destro",
         "BOOT": "Stivale",
         "MOTOR": "Motore",
         "RIVET": "Rivetto",
         "SUBCORTEX": "Sottocorteccia",

         "PRIME": "Prime",
         "WRAITH": "Wraith",
         "VANDAL": "Vandal",
         "CARMINE": "Carmine",
         }

EXCLUDED_ITEM_TRANSLATION = {
    "EQUINOX DAY ASPECT BLUEPRINT": "Schema Aspetto Giorno Equinox",
    "EQUINOX DAY CHASSIS BLUEPRINT": "Schema Chassis Giorno Equinox",
    "EQUINOX DAY NEUROPTICS BLUEPRINT": "Schema Neurottiche Giorno Equinox",
    "EQUINOX DAY SYSTEMS BLUEPRINT": "Schema Sistemi Giorno Equinox",
    "EQUINOX NIGHT ASPECT BLUEPRINT": "Schema Aspetto Notte Equinox",
    "EQUINOX NIGHT CHASSIS BLUEPRINT": "Schema Chassis Notte Equinox",
    "EQUINOX NIGHT NEUROPTICS BLUEPRINT": "Schema Neurottiche Notte Equinox",
    "EQUINOX NIGHT SYSTEMS BLUEPRINT": "Schema Sistemi Notte Equinox",
    "VITAL SYSTEMS BYPASS": "VITAL SYSTEMS BYPASS",
    "AMMO CHAIN": "AMMO CHAIN",
    "AMMO STOCK": "AMMO STOCK",
    "CATALYZER LINK": "CATALYZER LINK",
    "CARNIS CARAPACE": "CARNIS CARAPACE",
    "JUGULUS CARAPACE": "JUGULUS CARAPACE",
    "SAXUM CARAPACE": "SAXUM CARAPACE",
    "NARROW BARREL": "NARROW BARREL",
    "REFLEX GUARD": "REFLEX GUARD",
    "CONDUCTIVE BLADE": "CONDUCTIVE BLADE",
    "TEMPERED BLADE": "TEMPERED BLADE",
    "HYDRAULIC BARREL": "HYDRAULIC BARREL",
    "ELECTRIFIED BARREL": "ELECTRIFIED BARREL",
    "RUBEDO-LINED BARREL": "RUBEDO-LINED BARREL",
    "SPRING-LOADED CHAMBER": "SPRING-LOADED CHAMBER",
    "SPRING-LOADED BLADE": "SPRING-LOADED BLADE",
    "EMPOWERED BLADES": "EMPOWERED BLADES",
    "SHOCK COLLAR": "SHOCK COLLAR",
    "LUA BALCONY SCENE": "Scenario Balcone Lunare"
}


ITEM_NAME_IT = {

    # General Items
    "/Lotus/StoreItems/Types/Recipes/Components/OrokinReactorBlueprint": "Reattore Orokin (Schema)",
    "/Lotus/Types/Recipes/Components/OrokinReactorBlueprint": "Reattore Orokin (Schema)",
    "/Lotus/StoreItems/Types/Items/MiscItems/OrokinReactor": "Reattore Orokin",
    "/Lotus/Types/Items/MiscItems/OrokinReactor": "Reattore Orokin",
    "/Lotus/Types/Recipes/Components/OrokinCatalystBlueprint": "Catalizzatore Orokin (Schema)",
    "/Lotus/StoreItems/Types/Recipes/Components/OrokinCatalystBlueprint": "Catalizzatore Orokin (Schema)",
    "/Lotus/StoreItems/Types/Items/MiscItems/OrokinCatalyst": "Catalizzatore Orokin",
    "/Lotus/Types/Items/MiscItems/OrokinCatalyst": "Catalizzatore Orokin",
    "/Lotus/StoreItems/Upgrades/Mods/Fusers/LegendaryModFuser": "Legendary Core",
    "/Lotus/Types/Recipes/Components/FormaBlueprint": "Forma (Schema)",
    "/Lotus/StoreItems/Types/Recipes/Components/FormaBlueprint": "Forma (Schema)",
    "/Lotus/Types/Items/MiscItems/Forma": "Forma",
    "/Lotus/Types/Items/MiscItems/FormaAura": "Forma Aura",
    "/Lotus/StoreItems/Types/Items/MiscItems/FormaAura": "Forma Aura",
    "/Lotus/StoreItems/Types/Recipes/Components/FormaAuraBlueprint": "Forma Aura (Schema)",
    "/Lotus/StoreItems/Types/Items/MiscItems/FormaUmbra": "Forma Umbra",
    "/Lotus/Types/Items/MiscItems/FormaUmbra": "Forma Umbra",
    "/Lotus/StoreItems/Types/Recipes/Components/UmbraFormaBlueprint": "Umbra Forma (Schema)",
    "/Lotus/StoreItems/Types/Recipes/Components/UtilityUnlockerBlueprint": "Adattatore Exilus (Schema)",
    "/Lotus/Types/Recipes/Components/UtilityUnlockerBlueprint": "Adattatore Exilus (Schema)",
    "/Lotus/StoreItems/Types/Items/MiscItems/UtilityUnlocker": "Adattatore Exilus",
    "/Lotus/Types/Items/MiscItems/UtilityUnlocker": "Adattatore Exilus",
    "/Lotus/StoreItems/Types/Recipes/Components/WeaponUtilityUnlockerBlueprint": "Adattatore Exilus Arma (Schema)",
    "/Lotus/StoreItems/Types/Game/KubrowPet/Eggs/KubrowEgg": "Uovo Kubrow",
    "/Lotus/Types/Game/CatbrowPet/CatbrowGeneticSignature": "Codice Genetico Kavat",
    "/Lotus/Types/StoreItems/Packages/OrokinReactorAndCatalystBundle": "Pacchetto Potenziamento Orokin",
    "/Lotus/StoreItems/Types/BoosterPacks/UncommonArtifactPack": "Pacchetto Mod Falcone",
    "/Lotus/StoreItems/Types/BoosterPacks/PremiumRareArtifactPack": "Pacchetto Mod Drago",


    # Consumables
    "/Lotus/StoreItems/Types/Restoratives/Consumable/HunterTool": "Trappola Sifone Cinetico",
    "/Lotus/StoreItems/Types/Restoratives/Consumable/Scanner": "Codex Scanner",
    "/Lotus/StoreItems/Types/Restoratives/Consumable/LibraryScanner": "Scanner Sintetizzatore",
    "/Lotus/StoreItems/Types/Restoratives/Consumable/RazorbackCipher": "Cipher Razorback",
    "/Lotus/StoreItems/Types/Restoratives/Consumable/FomorianNegator": "Sabotatore Fomorian",
    "/Lotus/StoreItems/Types/Keys/MummyQuest/MummyArtifact01GearItem": "Urna di Inaros",
    "/Lotus/StoreItems/Types/Restoratives/Consumable/InfestedBaitBall": "Capsule Pherliac",
    "/Lotus/StoreItems/Types/Restoratives/TitaniaQuest/SpecterSummonKnaveLoki": "Apothic Nightfall",
    "/Lotus/StoreItems/Types/Restoratives/TitaniaQuest/SpecterSummonOrphidSaryn": "Apothic Twilight",
    "/Lotus/StoreItems/Types/Restoratives/TitaniaQuest/SpecterSummonFeyarchOberon": "Apothic Sunrise",
    "/Lotus/Types/Items/MiscItems/InstantSalvageRepairItem": "Drone da Riparazione Immediata",
    "/Lotus/StoreItems/Types/Restoratives/ScenarioBeacon": "OpLink",
    "/Lotus/StoreItems/Types/Keys/MummyQuestKeyBlueprint": "Sabbie di Inaros",
    "/Lotus/Types/StoreItems/Boosters/CreditBooster3DayStoreItem": "Booster Crediti 3 Giorni",
    "/Lotus/Types/StoreItems/Packages/ThreeDayCreditPack": "Booster Crediti 3 Giorni",
    "/Lotus/Types/StoreItems/Boosters/ResourceAmount3DayStoreItem": "Booster Risorse 3 Giorni",
    "/Lotus/Types/StoreItems/Packages/ThreeDayResourcePack": "Booster Risorse 3 Giorni",
    "/Lotus/Types/StoreItems/Boosters/AffinityBooster3DayStoreItem": "Booster Affinità 3 Giorni",
    "/Lotus/Types/StoreItems/Packages/ThreeDayAffinityPack": "Booster Affinità 3 Giorni",
    "/Lotus/Types/StoreItems/Boosters/ModDropChanceBooster3DayStoreItem": "Booster Probabilità Mod 3 Giorni",
    "/Lotus/StoreItems/Types/Recipes/Components/CorruptedBombardBallBlueprint": "Schema Spettro Corrupted Bombard",
    "/Lotus/StoreItems/Types/Restoratives/Consumable/CorruptedHeavyGunnerBall": "Spettro Corrupted Heavy Gunner",
    "/Lotus/StoreItems/Types/Restoratives/Consumable/BaroFireWorksCrate": "Fuochi d'Artificio Ki'Teer",
    "/Lotus/StoreItems/Types/Restoratives/Consumable/AssassinBait": "Esca Stalker",
    "/Lotus/StoreItems/Types/Restoratives/Consumable/AssassinBaitB": "Esca Zanuka",
    "/Lotus/StoreItems/Types/Restoratives/Consumable/AssassinBaitC": "Esca Grustrag Three",


    # Resources
    "/Lotus/Types/Items/MiscItems/Ferrite": "Ferrite",
    "/Lotus/Types/Items/MiscItems/Nanospores": "Nanospore",
    "/Lotus/Types/Items/MiscItems/PolymerBundle": "Kit Polimeri",
    "/Lotus/Types/Items/MiscItems/Neurode": "Neurode",
    "/Lotus/Types/Items/MiscItems/Salvage": "Rottami",
    "/Lotus/Types/Items/MiscItems/Circuits": "Circuiti",
    "/Lotus/Types/Items/MiscItems/Rubedo": "Rubedo",
    "/Lotus/Types/Items/MiscItems/NeuralSensor": "Sensore Neurale",
    "/Lotus/Types/Items/MiscItems/Morphic": "Morfidi",
    "/Lotus/Types/Items/MiscItems/OxiumAlloy": "Oxium",
    "/Lotus/Types/Items/MiscItems/Plastids": "Plastidi",
    "/Lotus/Types/Items/MiscItems/Gallium": "Gallio",
    "/Lotus/Types/Items/MiscItems/ControlModule": "Modulo di Controllo",
    "/Lotus/Types/Items/MiscItems/OrokinCell": "Cella Orokin",
    "/Lotus/Types/Items/MiscItems/AlloyPlate": "Piastre in Lega",
    "/Lotus/Types/Items/MiscItems/Tellurium": "Tellurio",
    "/Lotus/Types/Items/MiscItems/Cryotic": "Cryotic",
    "/Lotus/Types/Items/MiscItems/Alertium": "Estratto Nitain",
    "/Lotus/Types/Items/MiscItems/OmegaIsotope": "Isotopo Omega",
    "/Lotus/Types/Items/MiscItems/OmegaIsotopePickup": "Isotopo Omega",
    "/Lotus/Types/Items/MiscItems/RazorbackCipher": "Cipher Razorback",
    "/Lotus/Types/Items/MiscItems/RazorbackCipherPartPickup": "Cipher Razorback",
    "/Lotus/Types/Items/MiscItems/ArgonCrystal": "Cristallo di Argon",
    "/Lotus/Types/Items/MiscItems/VoidTearDrop": "Tracce del Void",
    "/Lotus/Types/Items/MiscItems/InfestedAladCoordinate": "Coordinate Nav Mutualist",
    "/Lotus/Types/Items/Research/ChemComponent": "Iniettore di Detonite",
    "/Lotus/Types/Items/Research/EnergyComponent": "Fieldron",
    "/Lotus/Types/Items/Research/BioComponent": "Massa Mutagene",
    "/Lotus/Types/Items/MiscItems/Eventium": "Synthula",
    "/Lotus/Types/Items/MiscItems/Kuva": "Kuva",
    "/Lotus/StoreItems/Types/Items/MiscItems/Alertium": "Nitain",
    "/Lotus/Types/Gameplay/Eidolon/Resources/CetusWispItem": "Cetus Wisp",
    "/Lotus/Types/Items/MiscItems/WaterFightBucks": "Perle Nakak",
    "/Lotus/Types/Items/RailJackMiscItems/TitaniumRailJackItem": "Titanium",
    "/Lotus/Types/Items/MiscItems/NoraWolfCreds": "Wolf Cred",
    "/Lotus/Types/Items/MiscItems/NoraIntermissionFourCreds": "Cred Nora's Choice",


    # Weapon Parts
    "/Lotus/Types/Recipes/Weapons/DeraVandalBlueprint": "Dera Vandal (Schema)",
    "/Lotus/Types/Recipes/Weapons/WeaponParts/DeraVandalStock": "Dera Vandal Calcio",
    "/Lotus/Types/Recipes/Weapons/WeaponParts/DeraVandalReceiver": "Dera Vandal Castello",
    "/Lotus/Types/Recipes/Weapons/WeaponParts/DeraVandalBarrel": "Dera Vandal Canna",
    "/Lotus/Types/Recipes/Weapons/SnipetronVandalBlueprint": "Snipetron Vandal (Schema)",
    "/Lotus/Types/Recipes/Weapons/WeaponParts/SnipetronVandalBarrel": "Snipetron Vandal Canna",
    "/Lotus/Types/Recipes/Weapons/WeaponParts/SnipetronVandalReceiver": "Snipetron Vandal Castello",
    "/Lotus/Types/Recipes/Weapons/WeaponParts/SnipetronVandalStock": "Snipetron Vandal Calcio",
    "/Lotus/Types/Recipes/Weapons/StrunWraithBlueprint": "Strun Wraith (Schema)",
    "/Lotus/Types/Recipes/Weapons/WeaponParts/StrunWraithBarrel": "Strun Wraith Canna",
    "/Lotus/Types/Recipes/Weapons/WeaponParts/StrunWraithStock": "Strun Wraith Calcio",
    "/Lotus/Types/Recipes/Weapons/WeaponParts/StrunWraithReceiver": "Strun Wraith Castello",
    "/Lotus/Types/Recipes/Weapons/KarakWraithBlueprint": "Karak Wraith (Schema)",
    "/Lotus/Types/Recipes/Weapons/WeaponParts/KarakWraithReceiver": "Karak Wraith Castello",
    "/Lotus/Types/Recipes/Weapons/WeaponParts/KarakWraithBarrel": "Karak Wraith Canna",
    "/Lotus/Types/Recipes/Weapons/WeaponParts/KarakWraithStock": "Karak Wraith Calcio",
    "/Lotus/Types/Recipes/Weapons/LatronWraithBlueprint": "Latron Wraith (Schema)",
    "/Lotus/Types/Recipes/Weapons/WeaponParts/LatronWraithBarrel": "Latron Wraith Canna",
    "/Lotus/Types/Recipes/Weapons/WeaponParts/LatronWraithStock": "Latron Wraith Calcio",
    "/Lotus/Types/Recipes/Weapons/WeaponParts/LatronWraithReceiver": "Latron Wraith Castello",
    "/Lotus/Types/Recipes/Weapons/TwinVipersWraithBlueprint": "Twin Vipers Wraith (Schema)",
    "/Lotus/Types/Recipes/Weapons/WeaponParts/TwinVipersWraithLink": "Twin Vipers Wraith Connettori",
    "/Lotus/Types/Recipes/Weapons/WeaponParts/TwinVipersWraithBarrel": "Twin Vipers Wraith Canna",
    "/Lotus/Types/Recipes/Weapons/WeaponParts/TwinVipersWraithReceiver": "Twin Vipers Wraith Castello",
    "/Lotus/Types/Recipes/Weapons/GrineerCombatKnifeSortieBlueprint": "Sheev (Schema)",
    "/Lotus/Types/Recipes/Weapons/WeaponParts/GrineerCombatKnifeHeatsink": "Sheev Dissipatore",
    "/Lotus/Types/Recipes/Weapons/WeaponParts/GrineerCombatKnifeHilt": "Sheev Elsa",
    "/Lotus/Types/Recipes/Weapons/WeaponParts/GrineerCombatKnifeBlade": "Sheev Lama",


    # Weapons
    "/Lotus/StoreItems/Types/Recipes/Weapons/PlasmaSwordBlueprint": "Plasma Sword (Schema)",
    "/Lotus/StoreItems/Types/Recipes/Weapons/PangolinSwordBlueprint": "Pangolin Sword (Schema)",
    "/Lotus/StoreItems/Types/Recipes/Weapons/HeatDaggerBlueprint": "Heat Dagger (Schema)",
    "/Lotus/StoreItems/Types/Recipes/Weapons/DarkDaggerBlueprint": "Dark Dagger (Schema)",
    "/Lotus/StoreItems/Types/Recipes/DarkSwordBlueprint": "Dark Sword (Schema)",
    "/Lotus/StoreItems/Types/Recipes/Weapons/HeatSwordBlueprint": "Heat Dagger (Schema)",
    "/Lotus/StoreItems/Types/Recipes/Weapons/CeramicDaggerBlueprint": "Ceramic Dagger (Schema)",
    "/Lotus/StoreItems/Types/Recipes/Weapons/JawBlueprint": "Jaw Sword (Schema)",
    "/Lotus/StoreItems/Types/Recipes/Weapons/GlaiveBlueprint": "Glaive (Schema)",
    "/Lotus/StoreItems/Weapons/Tenno/Pistols/DexFuris/DexFuris": "Dex Furis",
    "/Lotus/StoreItems/Weapons/Tenno/Melee/Swords/DexTheSecond/DexTheSecond": "Dex Dakra",
    "/Lotus/StoreItems/Weapons/Tenno/LongGuns/DexTheThird/DexTheThird": "Dex Sybaris",
    "/Lotus/StoreItems/Weapons/Corpus/LongGuns/Machinegun/SupraVandal": "Supra Vandal",
    "/Lotus/StoreItems/Weapons/Corpus/LongGuns/CrpBFG/Vandal/VandalCrpBFG": "Opticor Vandal",
    "/Lotus/StoreItems/Weapons/Corpus/Pistols/CorpusModularPistol/Vandal/CrpLaserPistolVandal": "Spectra Vandal",
    "/Lotus/StoreItems/Weapons/Corpus/LongGuns/CrpFreezeRay/Vandal/CrpFreezeRayVandalRifle": "Glaxion Vandal",
    "/Lotus/StoreItems/Weapons/Tenno/Pistols/ConclaveLeverPistol/ConclaveLeverPistol": "Zylok",
    "/Lotus/StoreItems/Weapons/Grineer/Melee/GrineerMachetteAndCleaver/WraithMacheteWeapon": "Machete Wraith",
    "/Lotus/StoreItems/Weapons/VoidTrader/VTDetron": "Detron Mara",
    "/Lotus/StoreItems/Weapons/VoidTrader/PrismaSkana": "Prisma Skana",
    "/Lotus/StoreItems/Weapons/VoidTrader/PrismaGrakata": "Prisma Grakata",
    "/Lotus/StoreItems/Weapons/Tenno/Archwing/Melee/VoidTraderArchsword/VTArchSwordWeapon": "Prisma Veritux",
    "/Lotus/StoreItems/Weapons/ClanTech/Energy/VandalElectroProd": "Prova Vandal",
    "/Lotus/StoreItems/Weapons/Grineer/LongGuns/GrineerSniperRifle/VulkarWraith": "Vulkar Wraith",
    "/Lotus/StoreItems/Weapons/Grineer/Melee/GrnBoomerang/HalikarWraithWeapon": "Halikar Wraith",
    "/Lotus/StoreItems/Weapons/Corpus/LongGuns/CorpusUMP/PrismaCorpusUMP": "Prisma Tetra",
    "/Lotus/StoreItems/Weapons/Grineer/LongGuns/VoidTraderGorgon/VTGorgon": "Prisma Gorgon",
    "/Lotus/StoreItems/Weapons/Corpus/Melee/KickAndPunch/PrismaObex": "Prisma Obex",
    "/Lotus/StoreItems/Weapons/Corpus/Pistols/CrpHandRL/PrismaAngstrum": "Prisma Angstrum",
    "/Lotus/StoreItems/Weapons/Grineer/Melee/GrineerMachetteAndCleaver/PrismaMachete": "Prisma Machete",
    "/Lotus/StoreItems/Weapons/Grineer/Pistols/WraithSingleViper/WraithSingleViper": "Wraith Viper",
    "/Lotus/StoreItems/Weapons/Grineer/Melee/GrineerMachetteAndCleaver/PrismaDualCleavers": "Prisma Dual Cleaver",
    "/Lotus/StoreItems/Weapons/Corpus/LongGuns/CrpShockRifle/QuantaVandal": "Quanta Vandal",
    "/Lotus/StoreItems/Weapons/Grineer/Pistols/GrineerBulbousSMG/Prisma/PrismaTwinGremlinsWeapon":
        "Prisma Twin Gremlins",
    "/Lotus/StoreItems/Weapons/ClanTech/Chemical/FlameThrowerWraith": "Ignis Wraith",
    "/Lotus/StoreItems/Weapons/Grineer/LongGuns/GrineerLeverActionRifle/PrismaGrinlokWeapon": "Prisma Grinlok",
    "/Lotus/StoreItems/Types/Recipes/Weapons/InfWarFanBlueprint": "Arum Spinosa (Schema)",
    "/Lotus/StoreItems/Types/Recipes/Weapons/InfSniperRifleBlueprint": "Sporothrix (Schema)",
    "/Lotus/StoreItems/Weapons/Tenno/Archwing/Primary/ArchwingHeavyPistols/Prisma/PrismaArchHeavyPistols":
        "Prisma Dual Decurion",
    "/Lotus/StoreItems/Weapons/Grineer/Melee/GunBlade/GrnGunBlade/GrnGunblade": "Vastilok",


    # Mods
    "/Lotus/Upgrades/Mods/FusionBundles/MarketTier3FusionBundle": "1000x Endo",
    "/Lotus/StoreItems/Upgrades/Mods/FusionBundles/RareFusionBundle": "80 Endo",
    "/Lotus/StoreItems/Upgrades/Mods/FusionBundles/AlertFusionBundleSmall": "80 Endo",
    "/Lotus/StoreItems/Upgrades/Mods/FusionBundles/AlertFusionBundleMedium": "100 Endo",
    "/Lotus/StoreItems/Upgrades/Mods/FusionBundles/AlertFusionBundleLarge": "150 Endo",
    "/Lotus/StoreItems/Upgrades/Mods/FusionBundles/NightwatchFusionBundle": "800 Endo",
    "/Lotus/StoreItems/Upgrades/Mods/Randomized/LotusRifleRandomModRare": "Riven Fucile",
    "/Lotus/StoreItems/Upgrades/Mods/Randomized/PlayerRifleWeaponRandomModRare": "Riven Fucile",
    "/Lotus/StoreItems/Upgrades/Mods/Randomized/LotusShotgunRandomModRare": "Riven Shotgun",
    "/Lotus/StoreItems/Upgrades/Mods/Randomized/PlayerShotgunWeaponRandomModRare": "Riven Shotgun",
    "/Lotus/StoreItems/Upgrades/Mods/Randomized/LotusPistolRandomModRare": "Riven Pistola",
    "/Lotus/StoreItems/Upgrades/Mods/Randomized/PlayerPistolWeaponRandomModRare": "Riven Pistola",
    "/Lotus/StoreItems/Upgrades/Mods/Randomized/LotusMeleeRandomModRare": "Riven Corpo a Corpo",
    "/Lotus/StoreItems/Upgrades/Mods/Randomized/PlayerMeleeWeaponRandomModRare": "Riven Corpo a Corpo",
    "/Lotus/StoreItems/Upgrades/Mods/Randomized/LotusModularPistolRandomModRare": "Riven Kitgun",
    "/Lotus/StoreItems/Upgrades/Mods/Randomized/LotusModularMeleeRandomModRare": "Riven Zaw",
    "/Lotus/StoreItems/Upgrades/Mods/Shotgun/DualStat/BlazeMod": "Blaze",
    "/Lotus/StoreItems/Upgrades/Mods/Pistol/DualStat/IceStormMod": "Ice Storm",
    "/Lotus/StoreItems/Upgrades/Mods/Warframe/DualStat/RunSpeedArmorMod": "Armored Agility",
    "/Lotus/StoreItems/Upgrades/Mods/Warframe/DualStat/FortitudeMod": "Fortitude",
    "/Lotus/StoreItems/Upgrades/Mods/Rifle/DualStat/HammerShotMod": "Hammer Shot",
    "/Lotus/StoreItems/Upgrades/Mods/Melee/DualStat/FocusEnergyMod": "Focus Energy",
    "/Lotus/StoreItems/Upgrades/Mods/Shotgun/DualStat/ReloadSpeedPunchThroughMod": "Seeking Fury",
    "/Lotus/StoreItems/Upgrades/Mods/Shotgun/DualStat/AcceleratedBlastMod": "Accelerated Blast",
    "/Lotus/StoreItems/Upgrades/Mods/Pistol/DualStat/StunningSpeedMod": "Stunning Speed",
    "/Lotus/StoreItems/Upgrades/Mods/Sentinel/SentinelLootRadarEnemyRadarMod": "Animal Instinct",
    "/Lotus/StoreItems/Upgrades/Mods/Rifle/DualStat/ShredMod": "Shred",
    "/Lotus/StoreItems/Upgrades/Mods/Warframe/DualStat/VigorMod": "Vigor",
    "/Lotus/StoreItems/Upgrades/Mods/Warframe/DualStat/ConstitutionMod": "Constitution",
    "/Lotus/StoreItems/Upgrades/Mods/Pistol/DualStat/GrinderMod": "Lethal Torrent",
    "/Lotus/StoreItems/Upgrades/Mods/Melee/DualStat/RendingStrikeMod": "Rending Strike",
    "/Lotus/StoreItems/Upgrades/Mods/Rifle/DualStat/WildfireMod": "Wildfire",
    "/Lotus/StoreItems/Upgrades/Mods/Aura/PlayerRifleDamageAuraMod": "Rifle Amp",
    "/Lotus/StoreItems/Upgrades/Mods/Aura/PlayerRifleAmmoAuraMod": "Rifle Scavenger",
    "/Lotus/StoreItems/Upgrades/Mods/Aura/PlayerSniperAmmoAuraMod": "Sniper Scavenger",
    "/Lotus/StoreItems/Upgrades/Mods/Aura/PlayerPistolAmmoAuraMod": "Pistol Scavenger",
    "/Lotus/StoreItems/Upgrades/Mods/Aura/PlayerShellAmmoAuraMod": "Shotgun Scavenger",
    "/Lotus/StoreItems/Upgrades/Mods/Aura/PlayerSniperDamageAuraMod": "Dead Eye",
    "/Lotus/StoreItems/Upgrades/Mods/Aura/EnemyArmorReductionAuraMod": "Corrosive Projection",
    "/Lotus/StoreItems/Upgrades/Mods/Aura/PlayerEnemyRadarAuraMod": "Enemy Radar",
    "/Lotus/StoreItems/Upgrades/Mods/Aura/PlayerEnergyRegenAuraMod": "Energy Siphon",
    "/Lotus/StoreItems/Upgrades/Mods/Aura/PlayerSprintAuraMod": "Sprint Boost",
    "/Lotus/StoreItems/Upgrades/Mods/Aura/PlayerHolsterSpeedAuraMod": "Speed Holster",
    "/Lotus/StoreItems/Upgrades/Mods/Aura/PlayerHealthRegenAuraMod": "Rejuvenation",
    "/Lotus/StoreItems/Upgrades/Mods/Aura/PlayerLootRadarAuraMod": "Loot Detector",
    "/Lotus/StoreItems/Upgrades/Mods/Aura/PlayerHealthAuraMod": "Physique",
    "/Lotus/StoreItems/Upgrades/Mods/Aura/EnemyShieldReductionAuraMod": "Shield Destruction",
    "/Lotus/StoreItems/Upgrades/Mods/Aura/RobotPoorAimAuraMod": "Emp Aura",
    "/Lotus/StoreItems/Upgrades/Mods/Aura/InfestationSpeedReductionAuraMod": "Infested Impedance",
    "/Lotus/StoreItems/Upgrades/Mods/Aura/PlayerMeleeAuraMod": "Steel Charge",
    "/Lotus/StoreItems/Upgrades/Mods/DualSource/Shotgun/ShotgunMedicMod": "Amalgam Shotgun Spazz",
    "/Lotus/StoreItems/Upgrades/Mods/DualSource/Rifle/SerratedRushMod": "Amalgam Serration",
    "/Lotus/StoreItems/Upgrades/Mods/DualSource/Pistol/MultishotDodgeMod": "Amalgam Barrel Diffusion",
    "/Lotus/StoreItems/Upgrades/Mods/DualSource/Melee/CritDamageChargeSpeedMod": "Amalgam Organ Shatter",
    "/Lotus/StoreItems/Upgrades/Mods/Rifle/EventSniperReloadDamageMod": "Primed Chamber",
    "/Lotus/StoreItems/Weapons/Tenno/Melee/MeleeTrees/ClawCmbTwoMeleeTree": "Vermilion Storm",
    "/Lotus/StoreItems/Weapons/Tenno/Melee/MeleeTrees/GlaiveCmbTwoMeleeTree": "Astral Twilight",
    "/Lotus/StoreItems/Weapons/Tenno/Melee/MeleeTrees/AxeCmbThreeMeleeTree": "Tempo Royale",
    "/Lotus/StoreItems/Upgrades/Mods/Rifle/DualStat/ElectEventRifleMod": "High Voltage",
    "/Lotus/StoreItems/Upgrades/Mods/Shotgun/DualStat/ElectEventShotgunMod": "Shell Shock",
    "/Lotus/StoreItems/Upgrades/Mods/Pistol/DualStat/ElectEventPistolMod": "Jolt",
    "/Lotus/StoreItems/Upgrades/Mods/Melee/DualStat/ElectEventMeleeMod": "Voltaic Strike",
    "/Lotus/StoreItems/Upgrades/Mods/Rifle/WeaponEventSlashDamageMod": "Fanged Fusillade",
    "/Lotus/StoreItems/Upgrades/Mods/Shotgun/WeaponEventSlashDamageMod": "Sweeping Serration",
    "/Lotus/StoreItems/Upgrades/Mods/Pistol/WeaponEventSlashDamageMod": "Maim",
    "/Lotus/StoreItems/Upgrades/Mods/Melee/WeaponEventSlashDamageMod": "Buzz Kill",
    "/Lotus/StoreItems/Upgrades/Mods/Rifle/WeaponEventRifleImpactDamageMod": "Crash Course",
    "/Lotus/StoreItems/Upgrades/Mods/Shotgun/WeaponEventShotgunImpactDamageMod": "Full Contact",
    "/Lotus/StoreItems/Upgrades/Mods/Pistol/WeaponEventPistolImpactDamageMod": "Pummel",
    "/Lotus/StoreItems/Upgrades/Mods/Melee/WeaponEventMeleeImpactDamageMod": "Collision Force",
    "/Lotus/StoreItems/Upgrades/Mods/Melee/WeaponGlaiveOnKillBuffSecondary": "Combo Fury",
    "/Lotus/StoreItems/Upgrades/Mods/Rifle/DualStat/FireEventRifleMod": "Thermite Rounds",
    "/Lotus/StoreItems/Upgrades/Mods/Shotgun/DualStat/FireEventShotgunMod": "Scattering Inferno",
    "/Lotus/StoreItems/Upgrades/Mods/Pistol/DualStat/FireEventPistolMod": "Scorch",
    "/Lotus/StoreItems/Upgrades/Mods/Melee/DualStat/FireEventMeleeMod": "Volcanic Edge",
    "/Lotus/StoreItems/Upgrades/Mods/Rifle/BowMultiShotOnHitMod": "Split Flight",
    "/Lotus/StoreItems/Upgrades/Mods/Melee/WeaponGlaiveSecondaryHeadshotKillMod": "Combo Killer",
    "/Lotus/StoreItems/Upgrades/Mods/Melee/WeaponGlaiveOnSixKillsBuffSecondary": "Mark of the Beast",

    # Primed Mods
    "/Lotus/StoreItems/Upgrades/Mods/Warframe/Expert/AvatarAbilityDurationModExpert": "Primed Continuity",
    "/Lotus/StoreItems/Upgrades/Mods/Warframe/Expert/AvatarPowerMaxModExpert": "Primed Flow",
    "/Lotus/StoreItems/Upgrades/Mods/Pistol/Expert/WeaponCritChanceModBeginnerExpert": "Primed Pistol Gambit",
    "/Lotus/StoreItems/Upgrades/Mods/Pistol/Expert/PrimedWeaponCritDamageMod": "Primed Target Cracker",
    "/Lotus/StoreItems/Upgrades/Mods/Rifle/Expert/WeaponFreezeDamageModExpert": "Primed Cryo Round",
    "/Lotus/StoreItems/Upgrades/Mods/Shotgun/Expert/WeaponCritDamageModExpert": "Primed Ravage",
    "/Lotus/StoreItems/Upgrades/Mods/Pistol/Expert/WeaponFireDamageModExpert": "Primed Heated Charge",
    "/Lotus/StoreItems/Upgrades/Mods/Melee/Expert/WeaponImpactDamageModExpert": "Primed Heavy Trauma",
    "/Lotus/StoreItems/Upgrades/Mods/Shotgun/Expert/WeaponDamageAmountModExpert": "Primed Point Blank",
    "/Lotus/StoreItems/Upgrades/Mods/Melee/Expert/WeaponMeleeRangeIncModExpert": "Primed Reach",
    "/Lotus/StoreItems/Upgrades/Mods/Rifle/Expert/WeaponReloadSpeedModExpert": "Primed Fast Hands",
    "/Lotus/StoreItems/Upgrades/Mods/Melee/Expert/WeaponMeleeDamageModExpert": "Primed Pressure Point",
    "/Lotus/StoreItems/Upgrades/Mods/Melee/Expert/WeaponToxinDamageModExpert": "Primed Fever Strike",
    "/Lotus/StoreItems/Upgrades/Mods/Shotgun/Expert/WeaponElectricityDamageModExpert": "Primed Charged Shell",
    "/Lotus/StoreItems/Types/Sentinels/SentinelPrecepts/PrimedRegen": "Primed Regen",
    "/Lotus/StoreItems/Upgrades/Mods/Archwing/Expert/ArchwingSuitAbilityStrengthModExpert":
        "Primed Morphic Transformer",
    "/Lotus/StoreItems/Upgrades/Mods/Pistol/Expert/WeaponClipMaxModExpert": "Primed Slip Magazine",
    "/Lotus/StoreItems/Upgrades/Mods/Rifle/Expert/WeaponRifleConvertAmmoModExpert": "Primed Rifle Ammo Mutation",
    "/Lotus/StoreItems/Upgrades/Mods/Shotgun/Expert/WeaponShotgunConvertAmmoModExpert": "Primed Shotgun Ammo Mutation",
    "/Lotus/StoreItems/Upgrades/Mods/Pistol/Expert/WeaponPistolConvertAmmoModExpert": "Primed Pistol Ammo Mutation",
    "/Lotus/StoreItems/Upgrades/Mods/Rifle/Expert/PrimedWeaponFactionDamageCorpus": "Primed Bane of Corpus",
    "/Lotus/StoreItems/Upgrades/Mods/Rifle/Expert/PrimedWeaponFactionDamageGrineer": "Primed Bane of Grineer",
    "/Lotus/StoreItems/Upgrades/Mods/Rifle/Expert/PrimedWeaponFactionDamageInfested": "Primed Bane of Infested",
    "/Lotus/StoreItems/Upgrades/Mods/Rifle/Expert/PrimedWeaponFactionDamageCorrupted": "Primed Bane of Corrupted",
    "/Lotus/StoreItems/Upgrades/Mods/Pistol/Expert/WeaponPistolFactionDamageCorruptedExpert": "Primed Expel Corrupted",
    "/Lotus/StoreItems/Upgrades/Mods/Pistol/Expert/WeaponPistolFactionDamageCorpusExpert": "Primed Expel Corpus",
    "/Lotus/StoreItems/Upgrades/Mods/Pistol/Expert/WeaponPistolFactionDamageGrineerExpert": "Primed Expel Grineer",
    "/Lotus/StoreItems/Upgrades/Mods/Pistol/Expert/WeaponPistolFactionDamageInfestedExpert": "Primed Expecl Infested",
    "/Lotus/StoreItems/Upgrades/Mods/Shotgun/Expert/WeaponShotgunFactionDamageGrineerExpert": "Primed Cleanse Grineer",
    "/Lotus/StoreItems/Upgrades/Mods/Shotgun/Expert/WeaponShotgunFactionDamageCorpusExpert": "Primed Cleanse Corpus",
    "/Lotus/StoreItems/Upgrades/Mods/Shotgun/Expert/WeaponShotgunFactionDamageInfestedExpert":
        "Primed Cleanse Infested",
    "/Lotus/StoreItems/Upgrades/Mods/Shotgun/Expert/WeaponShotgunFactionDamageCorruptedExpert":
        "Primed Cleanse Corrupted",
    "/Lotus/StoreItems/Upgrades/Mods/Melee/Expert/WeaponMeleeFactionDamageInfestedExpert": "Primed Smite Infested",
    "/Lotus/StoreItems/Upgrades/Mods/Melee/Expert/WeaponMeleeFactionDamageGrineerExpert": "Primed Smite Grineer",
    "/Lotus/StoreItems/Upgrades/Mods/Melee/Expert/WeaponMeleeFactionDamageCorruptedExpert": "Primed Smite Corrupted",
    "/Lotus/StoreItems/Upgrades/Mods/Melee/Expert/WeaponMeleeFactionDamageCorpusExpert": "Primed Smite Copus",
    "/Lotus/StoreItems/Upgrades/Mods/Sentinel/SentinelLootRadarEnemyRadarExpertMod": "Primed Animal Instinct",
    "/Lotus/StoreItems/Upgrades/Mods/Pistol/Expert/WeaponReloadSpeedModExpert": "Primed Quickdraw",
    "/Lotus/StoreItems/Upgrades/Mods/Sentinel/Kubrow/Expert/KubrowPackLeaderExpertMod": "Primed Pack Leader",
    "/Lotus/StoreItems/Upgrades/Mods/Rifle/Expert/WeaponIncreaseRadialExplosionModExpert": "Primed Firestorm",
    "/Lotus/StoreItems/Upgrades/Mods/Pistol/Event/AmbulasEvent/Expert/SecondaryExplosionRadiusModExpert":
        "Primed Fulmination",
    "/Lotus/StoreItems/Upgrades/Mods/Archwing/Rifle/Expert/ArchwingRifleDamageAmountModExpert":
        "Primed Rubedo-Lined Barrel",
    "/Lotus/StoreItems/Upgrades/Mods/Shotgun/Expert/WeaponFreezeDamageModExpert": "Primed Chilling Grasp",
    "/Lotus/StoreItems/Upgrades/Mods/Shotgun/Expert/WeaponReloadSpeedModExpert": "Primed Tactical Pump",
    "/Lotus/StoreItems/Upgrades/Mods/Rifle/Expert/WeaponClipMaxModExpert": "Primed Magazine Warp",
    "/Lotus/StoreItems/Upgrades/Mods/Shotgun/Expert/WeaponClipMaxModExpert": "Primed Ammo Stock",


    # Emblems
    "/Lotus/StoreItems/Upgrades/Skins/Clan/BountyHunterBadgeItem": "Emblema Stratos",
    "/Lotus/StoreItems/Upgrades/Skins/Clan/IndexEventBadgeItem": "Emblema Index",
    "/Lotus/StoreItems/Upgrades/Skins/Clan/DefectorRescueEventBadgeItem": "Emblema The Pacifism Defect",
    "/Lotus/StoreItems/Upgrades/Skins/Clan/OrbBadgeItem": "Emblema Buried Debts",
    "/Lotus/StoreItems/Upgrades/Skins/Clan/AmalgamEventBadgeItem": "Emblema Hostile Mergers",
    "/Lotus/StoreItems/Upgrades/Skins/Clan/BaroQuantumBadgeItem": "Ki'Teer Sekhara",
    "/Lotus/StoreItems/Upgrades/Skins/Clan/PrismaLotusEmblem": "Emblema Prisma Lotus",
    "/Lotus/StoreItems/Upgrades/Skins/Clan/BaroKubrowBadgeItem": "Emblema Pack Leader",
    "/Lotus/StoreItems/Upgrades/Skins/Clan/BaroKavatBadgeItem": "Emblema Glaring",
    "/Lotus/StoreItems/Upgrades/Skins/Clan/ScarletSpear/ScarletSpearOperationIEmblem":
        "Emblema Operazione Scarlet Spear I",
    "/Lotus/StoreItems/Upgrades/Skins/Clan/ScarletSpear/ScarletSpearOperationIIEmblem":
        "Emblema Operazione Scarlet Spear II",
    "/Lotus/StoreItems/Upgrades/Skins/Clan/ScarletSpear/ScarletSpearOperationIIIEmblem":
        "Emblema OperazioneScarlet Spear III",
    "/Lotus/StoreItems/Upgrades/Skins/Clan/MechEventEmblemItem": "Emblema Orphix Venom",
    "/Lotus/StoreItems/Types/Items/FusionTreasures/OroFusexJ": "Statua Ayatan Hemakara",
    "/Lotus/StoreItems/Upgrades/Skins/Clan/CNY2021EmblemItem": "Emblema Bue Rinnovo Lunare",
    "/Lotus/StoreItems/Upgrades/Skins/Clan/CNY2022EmblemItem": "Emblema Tigre Rinnovo Lunare",


    # Sigils
    "/Lotus/StoreItems/Upgrades/Skins/Sigils/EventSigilIndex": "Sigillo Index",
    "/Lotus/StoreItems/Upgrades/Skins/Sigils/DotD2016Sigil": "Sigillo Giorno dei Morti",
    "/Lotus/StoreItems/Upgrades/Skins/Sigils/HolidaySigilXmas2014A": "Sigillo Wreath",
    "/Lotus/StoreItems/Upgrades/Skins/Sigils/HolidaySigilXmas2014B": "Sigillo Nistlebrush",
    "/Lotus/StoreItems/Upgrades/Skins/Sigils/HolidaySigilXmas2014C": "Sigillo Tolling",
    "/Lotus/StoreItems/Upgrades/Skins/Sigils/HolidaySigilXmas2014D": "Sigillo Evergreen",
    "/Lotus/StoreItems/Upgrades/Skins/Sigils/ConclaveTacAlertSigilA": "Sigillo Quick Steel",
    "/Lotus/StoreItems/Upgrades/Skins/Sigils/OrbSigil": "Sigillo Buried Debts",
    "/Lotus/StoreItems/Upgrades/Skins/Sigils/RhinoDeluxeSigil": "Sigillo Rhino Palatine",
    "/Lotus/StoreItems/Upgrades/Skins/Sigils/EventSigilAmalgam": "Sigillo Hostile Mergers",
    "/Lotus/StoreItems/Upgrades/Skins/Sigils/PrimeTraderSigil": "Sigillo Prisma",
    "/Lotus/StoreItems/Upgrades/Skins/Sigils/BaroKubrowSigil": "Sigillo Capobranco",
    "/Lotus/StoreItems/Upgrades/Skins/Sigils/BaroKavatSigil": "Sigillo Glaring",
    "/Lotus/StoreItems/Upgrades/Skins/Sigils/PrismaLotusSigil": "Sigillo Prisma Lotus",
    "/Lotus/StoreItems/Upgrades/Skins/Sigils/WeGameNewYearOxSigil": "Sigillo Bue Rinnovo Lunare",
    "/Lotus/StoreItems/Upgrades/Skins/Sigils/WeGameNewYearFreeTigerSigil": "Sigillo Tigre Rinnovo Lunare",


    # Gliphs
    "/Lotus/StoreItems/Types/StoreItems/AvatarImages/ImageGrendelVED": "Glifo Grendel in Azione",
    "/Lotus/StoreItems/Types/StoreItems/AvatarImages/Winter2016VariantGlyph": "Glifo Conclave Solstice",
    "/Lotus/StoreItems/Types/StoreItems/AvatarImages/ImageBaroKiteer": "Glifo Baro Ki'Teer",
    "/Lotus/StoreItems/Types/StoreItems/AvatarImages/Seasonal/AvatarImageGlyphCookieKubrow": "Glifo Biscotto Kubrow",
    "/Lotus/StoreItems/Types/StoreItems/AvatarImages/Seasonal/AvatarImageGlyphCookieKavat": "Glifo Biscotto Kavat",
    "/Lotus/StoreItems/Types/StoreItems/AvatarImages/AvatarImageLowPolyKavat": "Glifo Prisma Kavat",
    "/Lotus/StoreItems/Types/StoreItems/AvatarImages/AvatarImageLowPolyKubrow": "Glifo Prisma Kubrow",
    "/Lotus/StoreItems/Types/StoreItems/AvatarImages/AvatarImageBaroIcon": "Glifo Tribute Baro Ki'Teer",
    "/Lotus/StoreItems/Types/StoreItems/AvatarImages/AvatarImageBaroTwoIcon": "Glifo Prisma Lotus",
    "/Lotus/StoreItems/Types/StoreItems/AvatarImages/ImagePopsicleGrineerPurple": "Glifo Dog Days",
    "/Lotus/StoreItems/Types/StoreItems/AvatarImages/Seasonal/Halloween2019GrendelTreat": "Glifo In Mah Belly",
    "/Lotus/StoreItems/Types/StoreItems/AvatarImages/ImageGaussVED": "Glifo Gauss in Azione",
    "/Lotus/StoreItems/Types/StoreItems/AvatarImages/AvatarImageProteaAction": "Glifo Protea in Azione",
    "/Lotus/StoreItems/Types/StoreItems/AvatarImages/ImageDexAnniversary": "Glifo Excalibur Dex in Azione",
    "/Lotus/StoreItems/Types/StoreItems/AvatarImages/AvatarImageXakuAction": "Glifo Xaku in Azione",
    "/Lotus/StoreItems/Types/StoreItems/AvatarImages/ChineseNewYear2021Glyph": "Glifo Criceto Banchettante",
    "/Lotus/StoreItems/Types/StoreItems/AvatarImages/AvatarImageSevagothAction": "Glifo Sevagoth in Azione",
    "/Lotus/StoreItems/Types/StoreItems/AvatarImages/ImageCalibanInAction": "Glifo Caliban in Azione",
    "/Lotus/StoreItems/Types/StoreItems/AvatarImages/TwinSnakesGlyph": "Glifo Vome-Fass",


    # Skins
    "/Lotus/StoreItems/Types/Recipes/Weapons/Skins/DaggerAxeBlueprint": "Skin Scindo Dagger Axe (Schema)",
    "/Lotus/StoreItems/Types/Recipes/Weapons/Skins/DualDaggerAxeBlueprint": "Skin Dual Zoren Dagger Axe (Schema)",
    "/Lotus/StoreItems/Types/Recipes/Weapons/Skins/GrnHammerBlueprint": "Skin Fragor Brokk Skin (Schema)",
    "/Lotus/StoreItems/Types/Recipes/Weapons/Skins/GrnAxeBlueprint": "Skin Scindo Manticore (Schema)",
    "/Lotus/StoreItems/Upgrades/Skins/Events/GlaxionPolar": "Skin Glaxion Polare",
    "/Lotus/StoreItems/Upgrades/Skins/Halloween/HalloweenDread": "Skin Dread Giorno dei Morti",
    "/Lotus/StoreItems/Upgrades/Skins/Excalibur/ExcaliburDexSkin": "Skin Excalibur Dex",
    "/Lotus/StoreItems/Upgrades/Skins/SummerSolstice/SummerIgnisSkin": "Skin Ignis Towsun",
    "/Lotus/StoreItems/Upgrades/Skins/Ornate/TekeluFragorSkin": "Skin Fragor Tekelu",
    "/Lotus/StoreItems/Upgrades/Skins/Weapons/Redeemer/RedeemerRelayWaterSkin": "Skin Redeemer Abysso",
    "/Lotus/StoreItems/Upgrades/Skins/WinterSolstice/SolsticeLenzSkin": "Skin Lenz Solstice",
    "/Lotus/StoreItems/Upgrades/Skins/WinterSolstice/SolsticeTatsuSkin": "Skin Tatsu Solstice",
    "/Lotus/StoreItems/Upgrades/Skins/Liset/LisetInsectSkinPrimeTrader": "Skin Mantis Prisma",
    "/Lotus/StoreItems/Upgrades/Skins/Liset/LisetSkinVoidTrader": "Skin Liset Prisma",
    "/Lotus/StoreItems/Upgrades/Skins/Liset/Gyroscope/LisetGyroscopeSkinPrimeTrader": "Skin Xiphos Prisma",
    "/Lotus/StoreItems/Upgrades/Skins/Liset/LisetBlueSkySkinPrimeTrader": "Skin Scimitar Prisma",
    "/Lotus/StoreItems/Upgrades/Skins/VoidTrader/ElixisOdonataSkin": "Skin Elixis Odonata",
    "/Lotus/StoreItems/Upgrades/Skins/VoidTrader/VTRedeemerSkin": "Skin Elixis Redeemer",
    "/Lotus/StoreItems/Upgrades/Skins/VoidTrader/ElixisSonicor": "Skin Elixis Sonicor",
    "/Lotus/StoreItems/Upgrades/Skins/VoidTrader/ElixisOpticor": "Skin Elixis Opticor",
    "/Lotus/StoreItems/Upgrades/Skins/Liset/InarosLisetSkin": "Skin Liset Cydonia",
    "/Lotus/StoreItems/Upgrades/Skins/VoidTrader/VTHalloweenDarkSword": "Skin Dark Sword Giorno dei Morti",
    "/Lotus/StoreItems/Upgrades/Skins/Pirate/HydroidAlternateSkin": "Hydroid Immortal Skin",
    "/Lotus/StoreItems/Upgrades/Skins/Tengu/ZephyrAlternateSkin": "Zephyr Immortal Skin",
    "/Lotus/StoreItems/Upgrades/Skins/Harlequin/MirageAlternateSkin": "Mirage Immortal Skin",
    "/Lotus/StoreItems/Upgrades/Skins/Cowgirl/MesaImmortallSkin": "Mesa Immortal Skin",
    "/Lotus/StoreItems/Upgrades/Skins/VoidTrader/VTQuanta": "Skin Quanta Aufeis",
    "/Lotus/StoreItems/Upgrades/Skins/Sentinels/Skins/DesertTaxonSkin": "Skin Desert Camo Taxon",
    "/Lotus/StoreItems/Upgrades/Skins/SummerSolstice/SummerSolsticeTwinGrakatas": "Skin Twin Grakata Towsun",
    "/Lotus/StoreItems/Upgrades/Skins/SummerSolstice/SummerSolsticeGorgon": "Skin Gorgon Towsun",
    "/Lotus/StoreItems/Upgrades/Skins/VoidTrader/BaroInarosPolearmSkin": "Skin Staffe Anpu",
    "/Lotus/StoreItems/Upgrades/Skins/Camo/DesertDirigaSkin": "Skin Diriga Desert-Camo",
    "/Lotus/StoreItems/Upgrades/Skins/VoidTrader/BaroArrow": "Skin Freccia Ki'Teer",
    "/Lotus/StoreItems/Upgrades/Skins/VoidTrader/PrismaArrow": "Freccia Prisma",
    "/Lotus/StoreItems/Upgrades/Skins/VoidTrader/ElixisTigris": "Skin Tigris Elixis",
    "/Lotus/StoreItems/Upgrades/Skins/Liset/LisetBlueSkySkinInaros": "Skin Scimitar Cydonia",
    "/Lotus/StoreItems/Upgrades/Skins/VoidTrader/BaroScytheMacheteSkin": "Skin Machete Syachid",
    "/Lotus/StoreItems/Upgrades/Skins/VoidTrader/ElixisBallasSword": "Skin Paracesis Elixis",
    "/Lotus/StoreItems/Upgrades/Skins/Magician/LimboImmortalSkin": "Limbo Immortal Skin",
    "/Lotus/StoreItems/Upgrades/Skins/VoidTrader/ElixisTiberon": "Skin Tiberon Elixis",
    "/Lotus/StoreItems/Upgrades/Skins/VoidTrader/ElixisLatronPistol": "Skin Pistola Latron Elixis",
    "/Lotus/StoreItems/Upgrades/Skins/Liset/LisetInsectSkinInaros": "Skin Liset Cydonia",
    "/Lotus/StoreItems/Upgrades/Skins/Events/AcolyteStalkerMios": "Skin Lacera Scorn",
    "/Lotus/StoreItems/Upgrades/Skins/Events/ArchRocketCrossbowGrineer": "Skin Fluctus Rahk",
    "/Lotus/StoreItems/UpTennoConBHUB6grades/Skins/Events/InfQuantaInfestedAladV": "Skin Paracyst Zebra",
    "/Lotus/StoreItems/Upgrades/Skins/Liset/DexLisetSkin": "Skin Dex Liset",
    "/Lotus/StoreItems/Upgrades/Skins/Dragon/ChromaAlternateSkin": "Skin Chroma Immortal",
    "/Lotus/StoreItems/Upgrades/Skins/WinterSolstice/SolsticeGaundaoSkin": "Skin Guandao Solstice",
    "/Lotus/StoreItems/Upgrades/Skins/Weapons/LongGuns/SolsticeBurston": "Skin Burston Solstice",
    "/Lotus/StoreItems/Upgrades/Skins/WinterSolstice/SolsticeCorinthSkin": "Skin Corinth Solstice",
    "/Lotus/StoreItems/Upgrades/Skins/MoaPet/BaroMoaPetSkin": "Skin Moa Ki'Teer",
    "/Lotus/StoreItems/Upgrades/Skins/Infestation/NidusAlternateSkin": "Skin Nidus Immortal",
    "/Lotus/StoreItems/Weapons/Tenno/Melee/Swords/TnShinaiSword/TnShinaiSwordSkin": "Skin Spada Tannukai",
    "/Lotus/StoreItems/Upgrades/Skins/Weapons/Staff/TnRibbonStaffSkin": "Skin Staffe Lemnas",
    "/Lotus/StoreItems/Upgrades/Skins/Weapons/DualSword/DualRibbonKamasSkin": "Skin Doppie Spade Lemnas",
    "/Lotus/StoreItems/Upgrades/Skins/Hoverboard/HoverboardStickerBaroA": "Scarabocchio K-Drive Ki'Teer Safari Blu",
    "/Lotus/StoreItems/Upgrades/Skins/Hoverboard/HoverboardStickerBaroB": "Scarabocchio K-Drive Ki'Teer Safari Verde",
    "/Lotus/StoreItems/Upgrades/Skins/Necramech/MechWeapon/MechEventMausolonSkin": "Skin Mausolon Supulchrax",
    "/Lotus/StoreItems/Upgrades/Skins/VoidTrader/AshLeverianLiosPistol": "Skin Pistola De Nas",
    "/Lotus/StoreItems/Upgrades/Skins/Glass/GaraAlternateSkin": "Skin Gara Immortal",

    # Sugatra
    "/Lotus/StoreItems/Upgrades/Skins/MeleeDangles/BaroInarosMeleeDangle": "Sugatra Anpu",
    "/Lotus/StoreItems/Upgrades/Skins/MeleeDangles/FireMeleeDangle": "Pyra Sugatra",
    "/Lotus/StoreItems/Upgrades/Skins/MeleeDangles/InfestedMeleeDangle": "Coccyst Sugatra",
    "/Lotus/StoreItems/Upgrades/Skins/MeleeDangles/BaroMeleeDangle": "Ki'Teer Sugatra",


    # Syandanas
    "/Lotus/StoreItems/Upgrades/Skins/Scarves/DexScarf": "Syandana Dex Nouchali",
    "/Lotus/StoreItems/Upgrades/Skins/Scarves/SolsticeCenturionCape": "Syandana Centuria Solstice",
    "/Lotus/StoreItems/Upgrades/Skins/Scarves/BaroCape": "Syandana Ki'Teer",
    "/Lotus/StoreItems/Upgrades/Skins/Scarves/KazBaroCape": "Syandana Diax Ki'Teer",
    "/Lotus/StoreItems/Upgrades/Skins/Scarves/VTHornSkullScarf": "Syandana Hecate Prisma",
    "/Lotus/StoreItems/Upgrades/Skins/Scarves/SolsticeBaroCape": "Syandana Solstice Ki'Teer",
    "/Lotus/StoreItems/Upgrades/Skins/Scarves/BaroCape2Scarf": "Syandana Ki'Teer Razza",
    "/Lotus/StoreItems/Upgrades/Skins/Scarves/VTDinoSpikeScarf": "Prisma Yamako",
    "/Lotus/StoreItems/Upgrades/Skins/Scarves/LisetScarf": "Syandana Domus",
    "/Lotus/StoreItems/Upgrades/Skins/Scarves/PrismaRazorScarf": "Prisma Uru Syandana",
    "/Lotus/StoreItems/Upgrades/Skins/Scarves/SolsticeGrnBannerScarf": "Stendardo Vanquished Solstice",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/FurisArmor/SolsticeFurisAArmor": "Syandana Centuria Solstice",
    "/Lotus/StoreItems/Upgrades/Skins/Scarves/SolsticeNelumboCape": "Syandana Wintercrest",


    # Armour Cosmetics
    "/Lotus/StoreItems/Upgrades/Skins/Armor/GrineerTurbines/WraithTurbinesArmArmor": "Spallacci Harkonar Wraith",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/GrineerTurbines/WraithTurbinesLegArmor": "Gambali Harkonar Wraith",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/GrineerTurbines/WraithTurbinesChestArmor": "Pettorina Harkonar Wraith",
    "/Lotus/StoreItems/Upgrades/Skins/Scarves/WraithTurbinesScarf": "Mantello Pettorina Harkonar Wraith",
    "/Lotus/StoreItems/Upgrades/Skins/Sentinels/Tails/BaroPetTail": "Coda Sentinella Ki'Teer",
    "/Lotus/StoreItems/Upgrades/Skins/Sentinels/Wings/BaroPetWings": "Ali Sentinella Ki'Teer",
    "/Lotus/StoreItems/Upgrades/Skins/Sentinels/Masks/BaroPetMask": "Maschera Sentinella Ki'Teer",
    "/Lotus/StoreItems/Upgrades/Skins/Sentinels/Wings/PrismaJetWings": "Ali Sentinella Jet Prisma Sinistre",
    "/Lotus/StoreItems/Upgrades/Skins/Sentinels/Wings/PrismaJetWingsRight": "Ali Sentinella Jet Prisma Destre",
    "/Lotus/StoreItems/Upgrades/Skins/Sentinels/Tails/PrismaFishTail": "Coda Sentinella Koi Prisma",
    "/Lotus/StoreItems/Upgrades/Skins/Sentinels/Tails/FishTail": "Coda Koi Sentinella",
    "/Lotus/StoreItems/Upgrades/Skins/Sentinels/Masks/PrismaMechHeadMask": "Maschera Sentinella Mech Prisma",
    "/Lotus/StoreItems/Upgrades/Skins/Sentinels/Masks/KavatPetMask": "Maschera Sentinella Kavat",
    "/Lotus/StoreItems/Upgrades/Skins/Sentinels/Wings/KavatPetWings": "Ali Sentinella Kavat",
    "/Lotus/StoreItems/Upgrades/Skins/Sentinels/Tails/KavatPetTail": "Coda Sentinella Kavat",
    "/Lotus/StoreItems/Types/Game/KubrowPet/Patterns/KubrowPetPatternPrimeTraderA": "Pattern Pelo Nexus",
    "/Lotus/Types/StoreItems/Packages/KavatColorPackNexus": "Kit Genetico-Estetico Nexus",
    "/Lotus/StoreItems/Upgrades/Skins/Kubrows/Armor/KubrowArmorBaro": "Armatura Kubrow Ki'Teer",
    "/Lotus/StoreItems/Upgrades/Skins/Catbrows/Armor/CatbrowArmorVoidTraderA": "Armatura Kavat Ki'Teer",
    "/Lotus/StoreItems/Upgrades/Skins/Catbrows/Armor/CatbrowArmorHalloweenA": "Armatura Kavat Giorno dei Morti",
    "/Lotus/StoreItems/Upgrades/Skins/Operator/Accessories/BaroHorn": "Diadema Cornu Baro Ki'Teer",
    "/Lotus/StoreItems/Upgrades/Skins/Operator/Accessories/EarpieceBaroA": "Orecchini Ki'Teer",
    "/Lotus/StoreItems/Upgrades/Skins/Operator/Accessories/EarpieceBaroB": "Orecchino Singolo Ki'Teer",
    "/Lotus/StoreItems/Upgrades/Skins/Operator/Accessories/EarpieceBaroC": "Orecchini Ki'Teer Atmos",
    "/Lotus/StoreItems/Upgrades/Skins/Operator/Accessories/BaroMouthPieceA": "Maschera Atmos Ki'Teer",
    "/Lotus/StoreItems/Upgrades/Skins/Operator/Accessories/BaroTiara": "Tiara Atmos Ki'Teer",
    "/Lotus/StoreItems/Upgrades/Skins/Operator/Accessories/BaroVisor": "Oculus Ki'Teer Atmos",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/SetTwoSamurai/VTSetTwoLegLeftArmor": "Spallaccio Sinistro Edo Prisma",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/SetTwoSamurai/VTSetTwoLegRightArmor": "Spallaccio Destro Edo Prisma",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/SetTwoSamurai/VTSetTwoArmLeftArmor": "Gambale Sinistro Edo Prisma",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/SetTwoSamurai/VTSetTwoArmRightArmor": "Gambale Destro Edo Prisma",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/SetTwoSamurai/VTSetTwoChestArmor": "Pettorale Edo Prisma",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/VTEos/VTEosChestArmor": "Pettorale Eos Prime",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/VTEos/VTEosALArmor": "Spallaccio Sinistro Eos Prime",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/VTEos/VTEosLLArmor": "Gambale Sinistro Eos Prime",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/VTEos/VTEosARArmor": "Spallaccio Destro Eos Prime",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/VTEos/VTEosLRArmor": "Gambale Destro Eos Prime",
    "/Lotus/Types/StoreItems/Packages/VTEosArmourBundle": "Set Armatura Eos Prime",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/SetThreeWinged/VTSetThreeChestArmor": "Pettorina Prisma Dedalus",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/SetThreeWinged/VTSetThreeArmLeftArmor":
        "Spallaccio Sinistro Prisma Dedalus",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/SetThreeWinged/VTSetThreeArmRightArmor": "Spallaccio Destro Prisma Dedalus",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/SetThreeWinged/VTSetThreeLegLeftArmor": "Gambale Sinistro Prisma Dedalus",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/SetThreeWinged/VTSetThreeLegRightArmor": "Gambale Destro Prisma Dedalus",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/BaroArmour/BaroArmourA": "Spallaccio Ki'Teer",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/BaroArmour/BaroArmourC": "Pettorina Ki'Teer",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/BaroArmour/BaroArmourL": "Gambali Ki'Teer",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/BaroArmourTwo/BaroArmourTwoA": "Spallacci Ki'Teer Foros",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/BaroArmourTwo/BaroArmourTwoL": "Gambali Ki'Teer Foros",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/BaroArmourTwo/BaroArmourTwoC": "Pettorina Ki'Teer Foros",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/Halloween2014Wings/PrismaNaberusArmArmor": "Prisma Naberus",
    "/Lotus/StoreItems/Upgrades/Skins/Kubrows/Armor/KubrowArmorPrisma": "Armatura Kubrow Rostam Prisma",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/FurisArmor/PrismaFurisCArmor": "Pettorina Prisma Ava",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/FurisArmor/PrismaFurisAArmor": "Spallaccio Prisma Ava",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/FurisArmor/PrismaFurisLArmor": "Gambali Prisma Ava",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/TnLatronArmor/TnLatronArmArmorPrisma": "Spallacci Latron Prisma",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/TnLatronArmor/TnLatronLegArmorPrisma": "Gambali Latron Prisma",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/TnLatronArmor/TnLatronChestArmorPrisma": "Pettorina Latron Prisma",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/TnLatronArmor/TnLatronChestArmorElixis": "Spallacci Latron Elixis",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/TnLatronArmor/TnLatronLegArmorElixis": "Gambali Latron Elixis",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/TnLatronArmor/TnLatronArmArmorElixis": "Pettorina Latron Elixis",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/Dex2020Armor/Dex2020ArmorAArmor": "Spallacci Dex Raksaka",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/Dex2020Armor/Dex2020ArmorCArmor": "Pettorina Dex Raksaka",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/Dex2020Armor/Dex2020ArmorLArmor": "Ginocchiere Dex Raksaka",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/NecraArmor/NecraArmorC": "Pettorina Mulciber",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/NecraArmor/NecraArmorL": "Gambale Mulciber",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/NecraArmor/NecraArmorA": "Spallaccio Mulciber",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/TnShinaiArmor/TnShinaiArmorA": "Spallacci Tannukai",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/TnShinaiArmor/TnShinaiArmorC": "Pettorina Tannukai",
    "/Lotus/StoreItems/Upgrades/Skins/Armor/TnShinaiArmor/TnShinaiArmorL": "Gambali Tannukai",


    # Ephemera
    "/Lotus/StoreItems/Upgrades/Skins/Effects/BatsEphemera": "Ephemera Naberus",
    "/Lotus/StoreItems/Upgrades/Skins/Effects/BaroEphemeraA": "Ephemera Ki'Teer",
    "/Lotus/StoreItems/Upgrades/Skins/Effects/FootstepsMaple": "Ephemera Fae Path",
    "/Lotus/StoreItems/Upgrades/Skins/Effects/LotusFlowers": "Lotus Ephemera",


    # Decorations
    "/Lotus/StoreItems/Types/Items/ShipDecos/ConclaveOroOrnament": "Ornamento Oro",
    "/Lotus/StoreItems/Types/Items/ShipDecos/ConclaveHeartOroOrnament": "Ornamento Eros Oro",
    "/Lotus/StoreItems/Types/Items/ShipDecos/ExcaliburArchwingBobbleHead": "Statuetta Excalibur con Archwing",
    "/Lotus/StoreItems/Types/Items/ShipDecos/BaroKiTeerBobbleHead": "Statuetta Baro Ki'Teer",
    "/Lotus/StoreItems/Types/Items/ShipDecos/PedistalPrime": "Piedistallo Prime",
    "/Lotus/StoreItems/Types/Items/ShipDecos/OrbiterPictureFrameBaro": "Display - Argyle",
    "/Lotus/StoreItems/Types/Items/ShipDecos/LisetPropOstRugBaro": "Tenno Kindred Rug",
    "/Lotus/StoreItems/Types/Items/ShipDecos/KubrowBust": "Busto Kubrow Bronzo",
    "/Lotus/StoreItems/Types/Items/ShipDecos/KubrowKavatLowPolyPoster": "Poster Prisma Companion",
    "/Lotus/StoreItems/Types/Items/ShipDecos/KavatBust": "Busto Bronzo Kavat",
    "/Lotus/StoreItems/Types/Items/ShipDecos/Plushies/PlushyDesertSkate": "Floof Desert Skate",
    "/Lotus/StoreItems/Types/Items/ShipDecos/BaroKiTeerDecorationA": "Ornamento Mahd Luxxum",
    "/Lotus/StoreItems/Types/Items/ShipDecos/BaroKiTeerDecorationB": "Ornamento Akka Luxxum",
    "/Lotus/StoreItems/Types/Items/ShipDecos/BaroKiTeerDecorationC": "Ornamento Zag Luxxum",
    "/Lotus/StoreItems/Types/Items/ShipDecos/BaroKiTeerDecorationD": "Ornamento Dvad Luxxum",
    "/Lotus/StoreItems/Types/Items/ShipDecos/BaroKiTeerDecorationE": "Ornamento Asra Luxxum",
    "/Lotus/StoreItems/Types/Items/ShipDecos/BaroKiTeerDecorationF": "Ornamento Puspa Luxxum",
    "/Lotus/StoreItems/Types/Items/ShipDecos/BaroKiTeerDecorationG": "Ornamento Sima Luxxum",
    "/Lotus/StoreItems/Types/Items/ShipDecos/BaroKiTeerDecorationH": "Ornamento Vez Luxxum",
    "/Lotus/StoreItems/Types/Items/ShipDecos/ParazonPoster": "Poster Parazon",
    "/Lotus/StoreItems/Types/Items/ShipDecos/LisetPropCleaningDroneBaro": "Drone Karo Ki'Teer",
    "/Lotus/StoreItems/Types/Items/ShipDecos/ExcaliburDexBobbleHead": "Excalibur Dex Noggle",
    "/Lotus/StoreItems/Types/Items/ShipDecos/RelayHydroidBobbleHead": "Statuetta Noggle Hydroid Reprise",
    "/Lotus/StoreItems/Types/Items/ShipDecos/EmberBobbleHead": "Statuetta Noggle Ember",
    "/Lotus/StoreItems/Types/Items/ShipDecos/UmbraPedestal": "Piedistallo Umbra",
    "/Lotus/StoreItems/Types/Items/ShipDecos/TarotCardTennoConA": "Prex: Deimos Fass",
    "/Lotus/StoreItems/Types/Items/ShipDecos/TarotCardTennoConB": "Prex: Deimos Scissus",
    "/Lotus/StoreItems/Types/Items/ShipDecos/TarotCardTennoConC": "Prex: Deimos Velocipod",
    "/Lotus/StoreItems/Types/Items/ShipDecos/TarotCardTennoConD": "Prex: Deimos Flagellocanth",
    "/Lotus/StoreItems/Types/Items/ShipDecos/TarotCardTennoConE": "Prex: Deimos Lobotriscid",
    "/Lotus/StoreItems/Types/Items/ShipDecos/TarotCardTennoConF": "Prex: Deimos Jugulus",
    "/Lotus/StoreItems/Types/Items/ShipDecos/TarotCardTennoConG": "Prex: Deimos Saxum",
    "/Lotus/StoreItems/Types/Items/ShipDecos/TarotCardTennoConH": "Prex: Deimos Carnis",
    "/Lotus/StoreItems/Types/Items/ShipDecos/TarotCardTennoConI": "Prex: Xaku",
    "/Lotus/StoreItems/Types/Items/ShipDecos/TarotCardTennoConJ": "Prex: Deimos Kymaeros",
    "/Lotus/StoreItems/Types/Items/ShipDecos/LisetPropCleaningDrone": "Drone Domestico",
    "/Lotus/StoreItems/Types/Items/ShipDecos/CNY2021Poster": "Poster Calligrafia Rinnovo Lunare",
    "/Lotus/StoreItems/Types/Items/ShipDecos/GarvLatroxPoster": "Poster Garv & Latrox",
    "/Lotus/StoreItems/Types/Items/ShipDecos/Plushies/Deimos/PlushySunMonsterCommon": "Fluff Fass",
    "/Lotus/StoreItems/Types/Items/ShipDecos/Plushies/Deimos/PlushyMoonMonsterCommon": "Fluff Vome",
    "/Lotus/StoreItems/Types/Items/ShipDecos/HeartOfDeimosAlbumCoverPoster": "Rhapsody in Blu",
    "/Lotus/StoreItems/Types/Items/ShipDecos/LisetPropGrineerCutter": "Decorazione Caccia Cutter",
    "/Lotus/StoreItems/Types/Items/ShipDecos/LisetPropGrineerFlak": "Decorazione Caccia Flak",
    "/Lotus/StoreItems/Types/Items/ShipDecos/LisetPropGrineerTaktis": "Decorazione Caccia Tactis",


    # Sentinels
    "/Lotus/StoreItems/Types/Sentinels/SentinelPowersuits/PrismaShadePowerSuit": "Prisma Shade",


    # Relics
    "/Lotus/StoreItems/Types/Game/Projections/T4VoidProjectionPBronze": "Reliquia Axi A2",
    "/Lotus/StoreItems/Types/Game/Projections/T4VoidProjectionVoltOdonataPrimeBronze": "Reliquia Axi V8",
    "/Lotus/StoreItems/Types/Game/Projections/T3VoidProjectionVoltOdonataPrimeBronze": "Reliquia Neo O1",
    "/Lotus/StoreItems/Types/Game/Projections/T4VoidProjectionMagNovaVaultBBronze": "Reliquia Axi A5",
    "/Lotus/StoreItems/Types/Game/Projections/T4VoidProjectionIvaraPrimeABronze": "Reliquia Axi A5",
    "/Lotus/Types/Game/Projections/T5VoidProjectionImmortalABronze": "Reliquia Requiem I",
    "/Lotus/Types/Game/Projections/T5VoidProjectionImmortalBBronze": "Reliquia Requiem II",
    "/Lotus/Types/Game/Projections/T5VoidProjectionImmortalCBronze": "Reliquia Requiem III",
    "/Lotus/Types/Game/Projections/T5VoidProjectionImmortalDBronze": "Reliquia Requiem IV",
    "/Lotus/Types/Game/Projections/T2VoidProjectionAlertSarynPrimeBronze": "Reliquia Meso S9",
    "/Lotus/Types/Game/Projections/T3VoidProjectionAlertSarynPrimeBronze": "Reliquia Neo S10",
    "/Lotus/Types/Game/Projections/T4VoidProjectionAlertSarynPrimeBronze": "Reliquia Axi N6",


    # Emoticons
    "/Lotus/StoreItems/Types/Items/Emotes/BaroEmote": "Positura Ki'Teer",


    # Captura
    "/Lotus/StoreItems/Types/Items/MiscItems/PhotoboothTileInarosTomb": "Scenario Tomba di Inaros",
    "/Lotus/StoreItems/Types/Items/MiscItems/PhotoboothTileOrokinExtraction": "Scenario Estrazione Torre Orokin",
    "/Lotus/StoreItems/Types/Items/MiscItems/PhotoboothTileHydroidRelay": "Scenario Stazione Hydroid",


    # Color Pickers
    "/Lotus/StoreItems/Types/StoreItems/SuitCustomizations/ColourPickerKiteerItemA": "Paletta Colori Ki'Teer",
    "/Lotus/StoreItems/Types/StoreItems/SuitCustomizations/ColourPickerTwitchBItemA": "Eminence",


    # Stencil and Diorama
    "/Lotus/StoreItems/Types/Game/QuartersWallpapers/BaroWallpaper": "Ki'Teer Stencil",
    "/Lotus/StoreItems/Types/Game/ActionFigureDioramas/EmpyreanRegionADiorama": "Vignetta Empyrean",

}
